package rules

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

type Violation struct {
	Pos         token.Position
	Category    string
	Description string
	Suggestion  string
}

func (v Violation) String() string {
	var sb strings.Builder
	if v.Pos.IsValid() && v.Pos.Filename != "" {
		sb.WriteString(fmt.Sprintf("%s:%d:%d: ", v.Pos.Filename, v.Pos.Line, v.Pos.Column))
	}
	sb.WriteString(fmt.Sprintf("[%s] %s", v.Category, v.Description))
	if v.Suggestion != "" {
		sb.WriteString(fmt.Sprintf(" (Fix: %s)", v.Suggestion))
	}
	return sb.String()
}

type Verifier struct {
	fset       *token.FileSet
	violations []Violation
	fileCount  int
}

func NewVerifier() *Verifier {
	return &Verifier{
		fset: token.NewFileSet(),
	}
}

func (v *Verifier) Violations() []Violation {
	return v.violations
}

func (v *Verifier) FileCount() int {
	return v.fileCount
}

func (v *Verifier) addViolation(pos token.Position, category, desc, suggestion string) {
	v.violations = append(v.violations, Violation{
		Pos:         pos,
		Category:    category,
		Description: desc,
		Suggestion:  suggestion,
	})
}

// VerifyPath scans the root path recursively for Go files and checks all hexag rules.
func (v *Verifier) VerifyPath(root string) error {
	info, err := os.Stat(root)
	if err != nil {
		return fmt.Errorf("failed to stat path %s: %w", root, err)
	}

	if !info.IsDir() {
		if strings.HasSuffix(root, ".go") {
			v.fileCount++
			v.checkFile(root)
		}
		return nil
	}

	return filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		// Skip VCS, vendor, node_modules, and bin dirs
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "node_modules" || name == "bin" {
				return filepath.SkipDir
			}
			return nil
		}

		if strings.HasSuffix(path, ".go") {
			v.fileCount++
			v.checkFile(path)
		}

		return nil
	})
}

func (v *Verifier) checkFile(filePath string) {
	slashPath := filepath.ToSlash(filePath)
	baseName := filepath.Base(filePath)
	isTestFile := strings.HasSuffix(baseName, "_test.go")

	// 1. File Naming Rules (applied to files under internal/)
	if isInternalPath(slashPath) && !isGeneratedPath(slashPath) {
		v.checkFileName(filePath, baseName, isTestFile)
	}

	// Parse file AST
	src, err := os.ReadFile(filePath)
	if err != nil {
		v.addViolation(token.Position{Filename: filePath}, "Parser", fmt.Sprintf("Failed to read file: %v", err), "")
		return
	}

	fileNode, err := parser.ParseFile(v.fset, filePath, src, parser.ParseComments)
	if err != nil {
		v.addViolation(token.Position{Filename: filePath}, "Parser", fmt.Sprintf("Failed to parse Go file: %v", err), "")
		return
	}

	// Skip AST checks on generated files
	if isGeneratedFile(fileNode) {
		return
	}

	// 2. AST-based Rules
	v.checkAST(filePath, fileNode, isTestFile)
}

func isInternalPath(slashPath string) bool {
	return strings.Contains(slashPath, "/internal/") || strings.HasPrefix(slashPath, "internal/")
}

func isGeneratedPath(slashPath string) bool {
	return strings.Contains(slashPath, "/adapters/database/mongo/models/") ||
		strings.Contains(slashPath, "/ports/mocks/")
}

func isGeneratedFile(f *ast.File) bool {
	for _, commentGroup := range f.Comments {
		for _, comment := range commentGroup.List {
			text := strings.ToLower(comment.Text)
			if strings.Contains(text, "code generated by") && strings.Contains(text, "do not edit") {
				return true
			}
		}
	}
	return false
}

func (v *Verifier) checkFileName(filePath, baseName string, isTestFile bool) {
	pos := token.Position{Filename: filePath, Line: 1, Column: 1}

	// Rule: No uppercase characters in filename
	if baseName != strings.ToLower(baseName) {
		v.addViolation(pos, "File Names",
			fmt.Sprintf("Filename '%s' contains uppercase characters.", baseName),
			"Use lowercase single-word filename.")
	}

	// Rule: No underscores unless it's a test file (*_test.go)
	if !isTestFile && strings.Contains(baseName, "_") {
		v.addViolation(pos, "File Names",
			fmt.Sprintf("Filename '%s' contains forbidden underscore.", baseName),
			"Use single-word lowercase filename (e.g. 'service.go', 'handler.go', 'repository.go').")
	}

	// Rule: Banned kebab-case with role suffixes
	rolePattern := regexp.MustCompile(`-(service|handler|repository|repo|rules|model|models)\.go$`)
	if rolePattern.MatchString(baseName) {
		v.addViolation(pos, "File Names",
			fmt.Sprintf("Filename '%s' uses banned kebab-case with role suffix.", baseName),
			"Directory provides contextual scope; use role name directly (e.g. 'service.go', 'handler.go').")
	}

	// Rule: Banned repo abbreviation in filename
	if strings.HasSuffix(baseName, "repo.go") {
		v.addViolation(pos, "File Names",
			fmt.Sprintf("Filename '%s' uses forbidden abbreviation 'repo'.", baseName),
			"Use full word 'repository.go'.")
	}
}

func (v *Verifier) checkAST(filePath string, f *ast.File, isTestFile bool) {
	slashPath := filepath.ToSlash(filePath)
	isServiceDir := strings.Contains(slashPath, "/services/")
	isEndpointDir := strings.Contains(slashPath, "/adapters/endpoint/")
	isDatabaseDir := strings.Contains(slashPath, "/adapters/database/")
	isPortsDomain := strings.HasSuffix(slashPath, "internal/ports/domain.go")

	ast.Inspect(f, func(n ast.Node) bool {
		if n == nil {
			return true
		}

		switch node := n.(type) {
		case *ast.TypeSpec:
			v.checkTypeSpec(filePath, node, isServiceDir, isEndpointDir)

		case *ast.FuncDecl:
			v.checkFuncDecl(filePath, node, isServiceDir, isEndpointDir, isPortsDomain)

		case *ast.CallExpr:
			v.checkCallExpr(filePath, node, isServiceDir, isEndpointDir, isDatabaseDir, isTestFile)

		case *ast.BinaryExpr:
			v.checkBinaryExpr(filePath, node, isServiceDir)

		case *ast.SwitchStmt:
			v.checkSwitchStmt(filePath, node)

		case *ast.SelectorExpr:
			v.checkSelectorExpr(filePath, node)

		case *ast.ValueSpec:
			v.checkValueSpec(filePath, node)
		}

		return true
	})
}

func (v *Verifier) checkTypeSpec(filePath string, ts *ast.TypeSpec, isServiceDir, isEndpointDir bool) {
	pos := v.fset.Position(ts.Pos())
	st, isStruct := ts.Type.(*ast.StructType)
	if !isStruct || st.Fields == nil {
		return
	}

	// Check Service struct fields
	if isServiceDir && ts.Name.Name == "Service" {
		repoFields := 0

		for _, field := range st.Fields.List {
			typeStr := formatTypeExpr(field.Type)

			// Check for TransactionRunner stored on service struct
			if strings.Contains(typeStr, "TransactionRunner") {
				v.addViolation(pos, "Tx Runner",
					"Storing TransactionRunner as a field on service struct is forbidden.",
					"Call s.GetTransactionRunner().Run(...) via embedded ServiceBase.")
			}

			// Check if field is a repository
			if isRepositoryType(typeStr) {
				repoFields++
				for _, name := range field.Names {
					if name.Name != "repository" {
						v.addViolation(v.fset.Position(name.Pos()), "Service Struct",
							fmt.Sprintf("Primary repository field must be named 'repository', found '%s'.", name.Name),
							"Rename field to 'repository'.")
					}
				}
			}

			// Check sibling services: must be lowercase acronym
			if isSiblingServiceType(typeStr) {
				expectedAcronym := computeAcronym(typeStr)
				for _, name := range field.Names {
					if name.Name != expectedAcronym {
						v.addViolation(v.fset.Position(name.Pos()), "Sibling Services",
							fmt.Sprintf("Sibling service field '%s' of type '%s' must be named with lowercase acronym '%s'.",
								name.Name, typeStr, expectedAcronym),
							fmt.Sprintf("Rename field to '%s'.", expectedAcronym))
					}
				}
			}
		}

		if repoFields > 1 {
			v.addViolation(pos, "Service Struct",
				"Service struct holds multiple repository interfaces. Services must only hold their own repository.",
				"Inject sibling services instead of foreign repositories.")
		}
	}

	// Check Empty Response Structs in endpoint handlers
	if isEndpointDir && strings.HasSuffix(ts.Name.Name, "Response") {
		if len(st.Fields.List) == 0 {
			v.addViolation(pos, "HTTP Handlers",
				fmt.Sprintf("Empty response struct '%s' is forbidden.", ts.Name.Name),
				"Handlers returning no data must return hextransport.NewSuccessResponse().ToJSON(c) without arguments.")
		}
	}
}

func (v *Verifier) checkFuncDecl(filePath string, fn *ast.FuncDecl, isServiceDir, isEndpointDir, isPortsDomain bool) {
	pos := v.fset.Position(fn.Pos())

	// Check Service constructor
	if isServiceDir && fn.Name.Name == "NewService" && fn.Type.Params != nil {
		repoCount := 0
		for _, param := range fn.Type.Params.List {
			typeStr := formatTypeExpr(param.Type)
			if strings.Contains(typeStr, "TransactionRunner") {
				v.addViolation(pos, "Tx Runner",
					"Passing TransactionRunner to service constructor is forbidden.",
					"TransactionRunner is provided via ServiceContext.")
			}
			if isRepositoryType(typeStr) {
				repoCount++
			}
		}
		if repoCount > 1 {
			v.addViolation(pos, "Service Struct",
				"Injecting foreign repositories into service constructor is forbidden.",
				"Inject sibling services instead.")
		}
	}

	// Check setter injection on Service (With...)
	if isServiceDir && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		if strings.Contains(recvType, "Service") && strings.HasPrefix(fn.Name.Name, "With") {
			v.addViolation(pos, "Service Struct",
				fmt.Sprintf("Setter injection method '%s' is forbidden.", fn.Name.Name),
				"Inject all dependencies via constructor; cyclic dependencies are strictly prohibited.")
		}
	}

	// Check exported handler methods on Handler structs
	if isEndpointDir && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		if strings.HasSuffix(recvType, "Handler") && fn.Type.Params != nil {
			// Check if method takes fiber.Ctx
			for _, param := range fn.Type.Params.List {
				paramType := formatTypeExpr(param.Type)
				if strings.Contains(paramType, "Ctx") {
					if !ast.IsExported(fn.Name.Name) && fn.Name.Name != "Register" {
						v.addViolation(pos, "HTTP Handlers",
							fmt.Sprintf("Handler method '%s' must be exported.", fn.Name.Name),
							"Capitalize the method name (e.g. 'Get', 'Create').")
					}
					break
				}
			}
		}
	}

	// Check CollectionName singular snake_case in domain.go
	if isPortsDomain && fn.Name.Name == "CollectionName" && fn.Body != nil {
		for _, stmt := range fn.Body.List {
			retStmt, ok := stmt.(*ast.ReturnStmt)
			if !ok || len(retStmt.Results) == 0 {
				continue
			}
			lit, isLit := retStmt.Results[0].(*ast.BasicLit)
			if !isLit || lit.Kind != token.STRING {
				continue
			}
			name := strings.Trim(lit.Value, `"`)
			if isPluralCollection(name) {
				v.addViolation(pos, "Collections",
					fmt.Sprintf("Collection name '%s' appears to be plural.", name),
					"Collection names must be singular snake_case (e.g. 'user', not 'users').")
			}
		}
	}
}

func (v *Verifier) checkCallExpr(filePath string, call *ast.CallExpr, isServiceDir, isEndpointDir, isDatabaseDir, isTestFile bool) {
	pos := v.fset.Position(call.Pos())

	// Check time.Now() in services or endpoints (not tests)
	if (isServiceDir || isEndpointDir) && !isTestFile {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
			if ident, ok := sel.X.(*ast.Ident); ok && ident.Name == "time" && sel.Sel.Name == "Now" {
				v.addViolation(pos, "Time Handling",
					"Calling time.Now() in services/handlers is forbidden.",
					"Capture once via hextransport.RequestTime(c) and pass 'at time.Time' through.")
			}
		}
	}

	// Check c.Query(...) in endpoint handlers
	if isEndpointDir {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Query" {
			v.addViolation(pos, "HTTP Queries",
				"Direct query parameter access with c.Query(...) is forbidden.",
				"Bind query parameters via hextransport.BindQuery(c, &req).")
		}
	}

	// Check hardcoded db.Collection("...") in database repositories
	if isDatabaseDir {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Collection" && len(call.Args) > 0 {
			if lit, ok := call.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
				v.addViolation(pos, "Collections",
					fmt.Sprintf("Hardcoded collection name string %s is forbidden.", lit.Value),
					"Always use ports.<Entity>Model{}.CollectionName().")
			}
		}
	}

	// Check abbreviated getter method calls (e.g. .GetConnectionRepo())
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		name := sel.Sel.Name
		if strings.HasPrefix(name, "Get") && strings.HasSuffix(name, "Repo") {
			v.addViolation(pos, "Dependencies",
				fmt.Sprintf("Abbreviated getter method '%s' is forbidden.", name),
				fmt.Sprintf("Use full name '%ssitory()'.", name[:len(name)-4]))
		}
	}
}

func (v *Verifier) checkBinaryExpr(filePath string, bin *ast.BinaryExpr, isServiceDir bool) {
	pos := v.fset.Position(bin.Pos())

	// Check sentinel equality: err == ports.ErrNotFound or err != ports.ErrNotFound
	if bin.Op == token.EQL || bin.Op == token.NEQ {
		leftStr := exprToString(bin.X)
		rightStr := exprToString(bin.Y)

		if isErrSentinel(leftStr) || isErrSentinel(rightStr) {
			opStr := "=="
			if bin.Op == token.NEQ {
				opStr = "!="
			}
			v.addViolation(pos, "Sentinels",
				fmt.Sprintf("Direct sentinel comparison '%s %s %s' is forbidden.", leftStr, opStr, rightStr),
				fmt.Sprintf("Use errors.Is(err, %s).", getSentinelExpr(leftStr, rightStr)))
		}

		// Check nil checks on injected sibling services: if s.us == nil
		if isServiceDir {
			if isNilExpr(bin.X) && isServiceSelector(bin.Y) {
				v.addViolation(pos, "Sibling Services",
					fmt.Sprintf("Nil check '%s' on injected service is forbidden.", exprToString(bin.Y)),
					"Inject dependencies unconditionally; nil checks are forbidden.")
			} else if isNilExpr(bin.Y) && isServiceSelector(bin.X) {
				v.addViolation(pos, "Sibling Services",
					fmt.Sprintf("Nil check '%s' on injected service is forbidden.", exprToString(bin.X)),
					"Inject dependencies unconditionally; nil checks are forbidden.")
			}
		}
	}
}

func (v *Verifier) checkSwitchStmt(filePath string, sw *ast.SwitchStmt) {
	if sw.Tag == nil {
		return
	}
	tagStr := exprToString(sw.Tag)
	if tagStr == "err" || strings.HasSuffix(tagStr, "Err") || strings.HasSuffix(tagStr, "Error") {
		for _, stmt := range sw.Body.List {
			if cc, ok := stmt.(*ast.CaseClause); ok {
				for _, expr := range cc.List {
					exprStr := exprToString(expr)
					if isErrSentinel(exprStr) {
						v.addViolation(v.fset.Position(expr.Pos()), "Sentinels",
							fmt.Sprintf("Switch case on error sentinel '%s' is forbidden.", exprStr),
							"Use errors.Is(err, ...) instead of switch.")
					}
				}
			}
		}
	}
}

func (v *Verifier) checkSelectorExpr(filePath string, sel *ast.SelectorExpr) {
	// Check direct struct field access to *Repo: s.deps.ConnectionRepo
	name := sel.Sel.Name
	if strings.HasSuffix(name, "Repo") && name != "repo" && !strings.HasPrefix(name, "Get") {
		// Ignore package selectors like repo.SomeFunc
		if _, isIdent := sel.X.(*ast.Ident); !isIdent {
			v.addViolation(v.fset.Position(sel.Pos()), "Dependencies",
				fmt.Sprintf("Direct field access or abbreviated name '%s' is forbidden.", name),
				"Use full getter method like 'GetConnectionRepository()'.")
		}
	}
}

func (v *Verifier) checkValueSpec(filePath string, vs *ast.ValueSpec) {
	// Check for CollectionName = "..." constant or variable
	for _, name := range vs.Names {
		if name.Name == "CollectionName" {
			v.addViolation(v.fset.Position(name.Pos()), "Collections",
				"Defining 'CollectionName' as a string constant/variable is forbidden.",
				"Implement CollectionName() string on ports.<Entity>Model.")
		}
	}
}

// Helpers

func formatTypeExpr(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return formatTypeExpr(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + formatTypeExpr(t.X)
	default:
		return ""
	}
}

func isRepositoryType(typeStr string) bool {
	return strings.HasSuffix(typeStr, "Repository") && !strings.Contains(typeStr, "QueueRepository")
}

func isSiblingServiceType(typeStr string) bool {
	return strings.HasSuffix(typeStr, "Service") &&
		!strings.Contains(typeStr, "ServiceBase") &&
		!strings.Contains(typeStr, "QueueService")
}

func computeAcronym(typeStr string) string {
	parts := strings.Split(typeStr, ".")
	leaf := parts[len(parts)-1]
	leaf = strings.TrimPrefix(leaf, "*")

	var letters []rune
	for _, r := range leaf {
		if unicode.IsUpper(r) {
			letters = append(letters, unicode.ToLower(r))
		}
	}
	return string(letters)
}

func isErrSentinel(str string) bool {
	if strings.HasPrefix(str, "ports.Err") {
		return true
	}
	if strings.HasPrefix(str, "Err") && str != "Error" {
		return true
	}
	if strings.Contains(str, ".Err") {
		return true
	}
	return false
}

func getSentinelExpr(left, right string) string {
	if isErrSentinel(left) {
		return left
	}
	return right
}

func isNilExpr(expr ast.Expr) bool {
	if ident, ok := expr.(*ast.Ident); ok && ident.Name == "nil" {
		return true
	}
	return false
}

func isServiceSelector(expr ast.Expr) bool {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	fieldName := sel.Sel.Name
	if fieldName == "repository" || fieldName == "ServiceBase" || fieldName == "ctx" {
		return false
	}
	return isServiceAcronym(fieldName)
}

func isServiceAcronym(str string) bool {
	// e.g. us, cs, bcs, abcs, userService
	clean := str
	if idx := strings.LastIndex(str, "."); idx != -1 {
		clean = str[idx+1:]
	}
	if clean == "err" || clean == "ctx" || clean == "nil" || clean == "ok" {
		return false
	}
	if strings.HasSuffix(clean, "Service") || strings.HasSuffix(clean, "Svc") {
		return true
	}
	// 2 to 4 lowercase letters, e.g. "us", "cs", "bcs", "abcs"
	if len(clean) >= 2 && len(clean) <= 4 {
		for _, r := range clean {
			if !unicode.IsLower(r) {
				return false
			}
		}
		return true
	}
	return false
}

func isPluralCollection(name string) bool {
	if !strings.HasSuffix(name, "s") {
		return false
	}
	singularExceptions := map[string]bool{
		"status":   true,
		"address":  true,
		"access":   true,
		"process":  true,
		"bus":      true,
		"class":    true,
		"lens":     true,
		"basis":    true,
		"analysis": true,
		"canvas":   true,
		"compass":  true,
		"crisis":   true,
		"alias":    true,
		"bonus":    true,
		"news":     true,
		"series":   true,
		"species":  true,
	}
	return !singularExceptions[name]
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.BasicLit:
		return e.Value
	default:
		return ""
	}
}
