all: false
dir: '{{.InterfaceDir}}/mocks'
filename: "mocks.go"
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: 'mocks'
recursive: false
template: testify
packages:
    "{{MODULE_PATH}}/internal/ports":
        config:
            all: true
