package generator

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/king-glitch/hexag/framework/cmd/brunogen/internal/parser"
)

// WriteMarkdown renders a single API.md contract reference grouped by route
// group (mirroring the .bru folder layout's top level), generated from the
// exact same parsed routes + example values as the Bruno collection.
func WriteMarkdown(routes []parser.Route, basePath, outFile, title string) error {
	groups := map[string][]parser.Route{}
	for _, r := range routes {
		key := strings.Join(r.GroupSegments, "/")
		groups[key] = append(groups[key], r)
	}

	var groupNames []string
	for g := range groups {
		groupNames = append(groupNames, g)
	}
	sort.Strings(groupNames)

	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", title)
	b.WriteString("Generated by `brunogen` from the backend's Fiber routes — do not hand-edit, regenerate instead.\n\n")
	fmt.Fprintf(&b, "Base URL: `%s`\n\n", basePath)
	b.WriteString("Auth: `Authorization: Bearer <token>` header, obtained from `POST /identity/phone-verification/verify`.\n\n")

	for _, g := range groupNames {
		fmt.Fprintf(&b, "## /%s\n\n", g)
		for _, route := range groups[g] {
			writeEndpoint(&b, route, basePath)
		}
	}

	return os.WriteFile(outFile, []byte(b.String()), 0644)
}

func writeEndpoint(b *strings.Builder, route parser.Route, basePath string) {
	fullSegments := append(append([]string{}, route.GroupSegments...), route.PathSegments...)
	path := basePath + "/" + strings.Join(fullSegments, "/")

	fmt.Fprintf(b, "### %s %s\n\n", route.Method, path)
	if route.Doc != "" {
		fmt.Fprintf(b, "%s\n\n", route.Doc)
	}
	if route.RequiresAuth {
		b.WriteString("Auth: required\n\n")
	} else {
		b.WriteString("Auth: none\n\n")
	}

	switch {
	case route.RequestBind == "body" && len(route.RequestFields) > 0:
		b.WriteString("Request body:\n\n```json\n")
		if s, err := marshalIndent(orderedObject(ExampleObject(route.RequestFields))); err == nil {
			b.WriteString(s)
		}
		b.WriteString("\n```\n\n")
	case (route.RequestBind == "query" || route.RequestBind == "pagination") && len(route.RequestFields) > 0:
		b.WriteString("Query params:\n\n| key | example |\n|---|---|\n")
		for _, kv := range ExampleObject(route.RequestFields) {
			fmt.Fprintf(b, "| `%s` | `%v` |\n", kv.Key, kv.Value)
		}
		b.WriteString("\n")
	default:
		b.WriteString("No request body.\n\n")
	}

	b.WriteString("Response:\n\n```json\n")
	if len(route.ResponseFields) > 0 {
		if s, err := marshalIndent(orderedObject([]KV{{Key: "data", Value: DataValue(route.ResponseFields)}})); err == nil {
			b.WriteString(s)
		}
	} else {
		b.WriteString("{\n  \"data\": null\n}")
	}
	b.WriteString("\n```\n\n")
}
