package rules

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

type Violation struct {
	Pos         token.Position
	Category    string
	Contract    string
	Description string
	Suggestion  string
}

func (v Violation) String() string {
	var sb strings.Builder
	if v.Pos.IsValid() && v.Pos.Filename != "" {
		sb.WriteString(fmt.Sprintf("%s:%d:%d: ", v.Pos.Filename, v.Pos.Line, v.Pos.Column))
	}
	sb.WriteString(fmt.Sprintf("[%s] %s", v.Category, v.Description))
	if v.Suggestion != "" {
		sb.WriteString(fmt.Sprintf(" (Fix: %s)", v.Suggestion))
	}
	return sb.String()
}

func (v Violation) Format(index, total int) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("[%d/%d] ❌ AGENTS.md Rule Violation: %s\n", index, total, v.Category))
	if v.Pos.IsValid() && v.Pos.Filename != "" {
		sb.WriteString(fmt.Sprintf("    Location: %s:%d:%d\n", v.Pos.Filename, v.Pos.Line, v.Pos.Column))
	}
	if v.Contract != "" {
		sb.WriteString(fmt.Sprintf("    Contract: %s\n", v.Contract))
	}
	sb.WriteString(fmt.Sprintf("    Problem:  %s\n", v.Description))
	if v.Suggestion != "" {
		sb.WriteString(fmt.Sprintf("    Fix:      %s\n", v.Suggestion))
	}
	return sb.String()
}

type enumConstant struct {
	name string
	pos  token.Position
}

type Verifier struct {
	fset                   *token.FileSet
	violations             []Violation
	fileCount              int
	portsEnumTypes         map[string]token.Position
	portsEnumMethods       map[string]bool
	portsEnumConstants     map[string][]enumConstant
	portsEnumHandledValues map[string]map[string]bool
	invariantsChecked      bool
}

func NewVerifier() *Verifier {
	return &Verifier{
		fset:                   token.NewFileSet(),
		portsEnumTypes:         make(map[string]token.Position),
		portsEnumMethods:       make(map[string]bool),
		portsEnumConstants:     make(map[string][]enumConstant),
		portsEnumHandledValues: make(map[string]map[string]bool),
	}
}

func (v *Verifier) Violations() []Violation {
	v.checkFinalInvariants()
	return v.violations
}

func (v *Verifier) FileCount() int {
	return v.fileCount
}

func (v *Verifier) addViolation(pos token.Position, category, contract, desc, suggestion string) {
	v.violations = append(v.violations, Violation{
		Pos:         pos,
		Category:    category,
		Contract:    contract,
		Description: desc,
		Suggestion:  suggestion,
	})
}

// VerifyPath scans the root path recursively for Go files and checks all hexag rules.
func (v *Verifier) VerifyPath(root string) error {
	info, err := os.Stat(root)
	if err != nil {
		return fmt.Errorf("failed to stat path %s: %w", root, err)
	}

	if !info.IsDir() {
		if strings.HasSuffix(root, ".go") {
			v.fileCount++
			v.checkFile(root)
		}
		return nil
	}

	return filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		// Skip VCS, vendor, node_modules, and bin dirs
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "node_modules" || name == "bin" {
				return filepath.SkipDir
			}
			return nil
		}

		if strings.HasSuffix(path, ".go") && !strings.HasSuffix(path, "_test.go") {
			v.fileCount++
			v.checkFile(path)
		}

		return nil
	})
}

func (v *Verifier) checkFile(filePath string) {
	slashPath := filepath.ToSlash(filePath)
	baseName := filepath.Base(filePath)

	// 1. File Naming Rules (applied to files under internal/)
	if isInternalPath(slashPath) && !isGeneratedPath(slashPath) {
		v.checkFileName(filePath, baseName)
	}

	// Parse file AST
	src, err := os.ReadFile(filePath)
	if err != nil {
		v.addViolation(
			token.Position{Filename: filePath},
			"Parser",
			"Source files must be readable Go code.",
			fmt.Sprintf("Failed to read file: %v", err),
			"Ensure file exists and has read permissions.",
		)
		return
	}

	fileNode, err := parser.ParseFile(v.fset, filePath, src, parser.ParseComments)
	if err != nil {
		v.addViolation(
			token.Position{Filename: filePath},
			"Parser",
			"Source files must compile and be valid Go syntax.",
			fmt.Sprintf("Failed to parse Go file: %v", err),
			"Fix syntax errors so AST parser can parse the file.",
		)
		return
	}

	// Skip AST checks on generated files
	if isGeneratedFile(fileNode) {
		return
	}

	// 2. AST-based Rules
	v.checkAST(filePath, fileNode)
}

func isInternalPath(slashPath string) bool {
	return strings.Contains(slashPath, "/internal/") || strings.HasPrefix(slashPath, "internal/")
}

func isGeneratedPath(slashPath string) bool {
	return strings.Contains(slashPath, "/adapters/database/mongo/models/") ||
		strings.Contains(slashPath, "/ports/mocks/")
}

func isGeneratedFile(f *ast.File) bool {
	for _, commentGroup := range f.Comments {
		for _, comment := range commentGroup.List {
			text := strings.ToLower(comment.Text)
			if strings.Contains(text, "code generated by") && strings.Contains(text, "do not edit") {
				return true
			}
		}
	}
	return false
}

func (v *Verifier) checkFileName(filePath, baseName string) {
	pos := token.Position{Filename: filePath, Line: 1, Column: 1}

	// Rule: No uppercase characters in filename
	if baseName != strings.ToLower(baseName) {
		v.addViolation(
			pos,
			"File Names",
			"Filenames must be single-word lowercase.",
			fmt.Sprintf("Filename '%s' contains uppercase characters.", baseName),
			fmt.Sprintf("Rename to lowercase '%s'.", strings.ToLower(baseName)),
		)
	}

	// Rule: No underscores
	prefix := strings.TrimSuffix(baseName, ".go")
	if strings.Contains(baseName, "_") {
		kebab := strings.ReplaceAll(baseName, "_", "-")
		v.addViolation(
			pos,
			"File Names",
			"Single-word lowercase filenames. The directory provides the contextual scope.",
			fmt.Sprintf("Filename '%s' contains forbidden underscore.", baseName),
			fmt.Sprintf("Rename to single-word lowercase (e.g. 'service.go', 'handler.go') or sibling kebab-case ('%s').", kebab),
		)
	}

	// Rule: Banned kebab-case with role suffixes
	nameToCheck := prefix + ".go"
	rolePattern := regexp.MustCompile(`-(service|handler|repository|repo|rules|model|models)\.go$`)
	if rolePattern.MatchString(nameToCheck) {
		v.addViolation(
			pos,
			"File Names",
			"The directory provides the contextual scope. Role files must be single-word lowercase.",
			fmt.Sprintf("Filename '%s' uses banned kebab-case with role suffix.", baseName),
			"Remove the domain prefix and name by role directly (e.g. 'service.go', 'handler.go', 'repository.go').",
		)
	}

	// Rule: Banned repo abbreviation in filename
	if strings.HasSuffix(nameToCheck, "repo.go") {
		v.addViolation(
			pos,
			"File Names",
			"Use full words for role files; abbreviations like 'repo' are forbidden.",
			fmt.Sprintf("Filename '%s' uses forbidden abbreviation 'repo'.", baseName),
			"Rename to 'repository.go'.",
		)
	}
}

func (v *Verifier) checkAST(filePath string, f *ast.File) {
	slashPath := filepath.ToSlash(filePath)
	isInternal := isInternalPath(slashPath)
	isServiceDir := strings.Contains(slashPath, "/services/")
	isEndpointDir := strings.Contains(slashPath, "/adapters/endpoint/")
	isDatabaseDir := strings.Contains(slashPath, "/adapters/database/")
	isPortsDomain := strings.HasSuffix(slashPath, "internal/ports/domain.go")
	isPortsDir := strings.Contains(slashPath, "/internal/ports/") && !strings.Contains(slashPath, "/internal/ports/mocks/")
	isConstantDir := strings.Contains(slashPath, "/internal/core/constant/") ||
		strings.Contains(slashPath, "/core/constant/") ||
		strings.Contains(slashPath, "/constant/") ||
		strings.Contains(slashPath, "/constants/")

	importedPackages := make(map[string]bool)
	for _, imp := range f.Imports {
		if imp.Name != nil {
			importedPackages[imp.Name.Name] = true
		} else {
			pathVal := strings.Trim(imp.Path.Value, `"`)
			parts := strings.Split(pathVal, "/")
			last := parts[len(parts)-1]
			importedPackages[last] = true
			if len(parts) >= 2 && len(last) >= 2 && last[0] == 'v' && unicode.IsDigit(rune(last[1])) {
				importedPackages[parts[len(parts)-2]] = true
			}
		}
	}

	callFunMap := make(map[*ast.SelectorExpr]bool)
	typeExprMap := make(map[*ast.SelectorExpr]bool)
	ast.Inspect(f, func(n ast.Node) bool {
		switch t := n.(type) {
		case *ast.CallExpr:
			if sel, ok := t.Fun.(*ast.SelectorExpr); ok {
				callFunMap[sel] = true
			}
		case *ast.Field:
			markTypeSelectors(t.Type, typeExprMap)
		case *ast.TypeSpec:
			markTypeSelectors(t.Type, typeExprMap)
		case *ast.ValueSpec:
			markTypeSelectors(t.Type, typeExprMap)
		case *ast.TypeAssertExpr:
			markTypeSelectors(t.Type, typeExprMap)
		}
		return true
	})

	ast.Inspect(f, func(n ast.Node) bool {
		if n == nil {
			return true
		}

		switch node := n.(type) {
		case *ast.GenDecl:
			v.checkGenDecl(filePath, node, isInternal, isPortsDir, isConstantDir)

		case *ast.TypeSpec:
			v.checkTypeSpec(filePath, node, isServiceDir, isEndpointDir)

		case *ast.FuncDecl:
			v.checkFuncDecl(filePath, node, isInternal, isServiceDir, isEndpointDir, isPortsDomain)

		case *ast.CallExpr:
			v.checkCallExpr(filePath, node, isInternal, isServiceDir, isEndpointDir, isDatabaseDir, importedPackages)

		case *ast.BinaryExpr:
			v.checkBinaryExpr(filePath, node, isInternal, isServiceDir)

		case *ast.AssignStmt:
			v.checkAssignStmt(filePath, node, isInternal)

		case *ast.SwitchStmt:
			v.checkSwitchStmt(filePath, node)

		case *ast.SelectorExpr:
			v.checkSelectorExpr(filePath, node, importedPackages, callFunMap[node], typeExprMap[node])

		case *ast.ValueSpec:
			v.checkValueSpec(filePath, node)
		}

		return true
	})

	// Struct accessor consistency: structs with Get...() methods must not have exported fields.
	if isInternal && !isPortsDir {
		structFields := collectStructFields(f)
		structGetters := collectGetterMethods(f)
		v.checkStructAccessorConsistency(filePath, structFields, structGetters)
	}
}

func (v *Verifier) checkGenDecl(filePath string, decl *ast.GenDecl, isInternal, isPortsDir, isConstantDir bool) {
	// Track enum types and constants in ports
	if isPortsDir && decl.Tok == token.CONST {
		lastType := ""
		for _, spec := range decl.Specs {
			if vs, ok := spec.(*ast.ValueSpec); ok {
				if vs.Type != nil {
					lastType = formatTypeExpr(vs.Type)
				} else if len(vs.Values) > 0 {
					lastType = ""
				}
				if lastType != "" && !strings.Contains(lastType, ".") && !isBuiltinGoType(lastType) {
					if _, exists := v.portsEnumTypes[lastType]; !exists {
						v.portsEnumTypes[lastType] = v.fset.Position(vs.Pos())
					}
					for _, name := range vs.Names {
						v.portsEnumConstants[lastType] = append(v.portsEnumConstants[lastType], enumConstant{
							name: name.Name,
							pos:  v.fset.Position(name.Pos()),
						})
					}
				}
			}
		}
	}

	// Check constants and enums outside their allowed locations
	if isInternal && !isPortsDir && decl.Tok == token.CONST {
		lastType := ""
		for _, spec := range decl.Specs {
			if vs, ok := spec.(*ast.ValueSpec); ok {
				if vs.Type != nil {
					lastType = formatTypeExpr(vs.Type)
				} else if len(vs.Values) > 0 {
					lastType = ""
				}
				isEnum := lastType != "" && !strings.Contains(lastType, ".") && !isBuiltinGoType(lastType)

				for _, name := range vs.Names {
					if name.Name == "_" || name.Name == "CollectionName" {
						continue
					}

					if isEnum {
						// Typed enums MUST be defined in internal/ports/ (never in constant/ or adapters)
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Enums",
							"All domain enums must be defined in 'internal/ports' and implement 'IsValid() bool'.",
							fmt.Sprintf("Domain enum '%s' (constant '%s') defined in '%s' outside internal/ports.", lastType, name.Name, filepath.Base(filePath)),
							fmt.Sprintf("Move enum '%s' and its constants to 'internal/ports/enum.go' and implement 'IsValid() bool'.", lastType),
						)
					} else if !isConstantDir {
						// Non-enum constants must be in the constant folder
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Constants",
							"Constants must be defined in the constant folder ('internal/core/constant/'). Defining local constants in adapter or service files is forbidden.",
							fmt.Sprintf("Constant '%s' defined in '%s' outside constant folder.", name.Name, filepath.Base(filePath)),
							fmt.Sprintf("Move constant '%s' to 'internal/core/constant/' (e.g. 'constant.go').", name.Name),
						)
					}
				}
			}
		}
	}

	// Check sentinel errors defined outside ports
	if isInternal && !isPortsDir && decl.Tok == token.VAR {
		for _, spec := range decl.Specs {
			if vs, ok := spec.(*ast.ValueSpec); ok {
				for i, val := range vs.Values {
					if call, ok := val.(*ast.CallExpr); ok && isErrorCreationCall(call) {
						name := ""
						if i < len(vs.Names) {
							name = vs.Names[i].Name
						}
						pos := v.fset.Position(val.Pos())
						if i < len(vs.Names) {
							pos = v.fset.Position(vs.Names[i].Pos())
						}
						v.addViolation(
							pos,
							"Sentinels",
							"Define project sentinels in 'internal/ports/errors.go'; defining local or package-level error variables outside ports is forbidden.",
							fmt.Sprintf("Sentinel error '%s' defined in '%s' outside internal/ports.", name, filepath.Base(filePath)),
							fmt.Sprintf("Move sentinel error '%s' to 'internal/ports/errors.go' (e.g. as 'ports.%s') and register it in init().", name, deriveSentinelName(name)),
						)
					}
				}
			}
		}
	}
}

func (v *Verifier) checkTypeSpec(filePath string, ts *ast.TypeSpec, isServiceDir, isEndpointDir bool) {
	pos := v.fset.Position(ts.Pos())
	st, isStruct := ts.Type.(*ast.StructType)
	if !isStruct || st.Fields == nil {
		return
	}

	slashPath := filepath.ToSlash(filePath)
	isInternal := strings.Contains(slashPath, "/internal/") || strings.HasPrefix(slashPath, "internal/")
	isMock := strings.Contains(slashPath, "/internal/ports/mocks/") || strings.Contains(slashPath, "/ports/mocks/")

	// Check Service struct fields
	if isServiceDir && ts.Name.Name == "Service" {
		repoFields := 0

		for _, field := range st.Fields.List {
			typeStr := formatTypeExpr(field.Type)

			// Check for TransactionRunner stored on service struct
			if strings.Contains(typeStr, "TransactionRunner") {
				v.addViolation(
					pos,
					"Tx Runner",
					"Never store TransactionRunner as a field on service structs.",
					"Storing TransactionRunner as a field on service struct is forbidden.",
					"Remove field and call 's.GetTransactionRunner().Run(ctx, func(txCtx context.Context) error { ... })' via embedded ServiceBase.",
				)
			}

			// Check if field is a repository
			if isRepositoryType(typeStr) {
				repoFields++
				for _, name := range field.Names {
					if name.Name != "repository" {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Service Struct",
							"In service structs, the service's primary repository field MUST be named 'repository'.",
							fmt.Sprintf("Primary repository field is named '%s' instead of 'repository'.", name.Name),
							fmt.Sprintf("Rename struct field '%s' to 'repository %s'.", name.Name, typeStr),
						)
					}
				}
			}

			// Check sibling services: must be lowercase acronym
			if isSiblingServiceType(typeStr) {
				expectedAcronym := computeAcronym(typeStr)
				for _, name := range field.Names {
					if !isValidServiceFieldName(name.Name, typeStr) {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Sibling Services",
							"Injected sibling services MUST be named by strict lowercase acronyms of their interface type.",
							fmt.Sprintf("Sibling service field '%s' of type '%s' does not use expected acronym '%s'.", name.Name, typeStr, expectedAcronym),
							fmt.Sprintf("Rename struct field '%s' to '%s %s'.", name.Name, expectedAcronym, typeStr),
						)
					}
				}
			}
		}

		if repoFields > 1 {
			v.addViolation(
				pos,
				"Service Struct",
				"A service must ONLY hold its own repository. Sibling domains must be accessed strictly through their service interface.",
				"Service struct holds multiple repository interfaces.",
				"Remove foreign repositories. Inject sibling service interfaces instead.",
			)
		}
	} else if isInternal && !isMock {
		// Check other structs in internal/ (e.g. Deps, Runner, Supervisor, etc.)
		for _, field := range st.Fields.List {
			typeStr := formatTypeExpr(field.Type)

			// Service fields in any internal struct must be unexported and use lowercase acronym
			if isSiblingServiceType(typeStr) {
				expectedAcronym := computeAcronym(typeStr)
				for _, name := range field.Names {
					if !isValidServiceFieldName(name.Name, typeStr) {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Sibling Services",
							"Service interface fields on structs must be unexported lowercase acronyms (e.g. 'cs ports.CreditService').",
							fmt.Sprintf("Service field '%s' of type '%s' on struct '%s' must be an unexported lowercase acronym '%s'.", name.Name, typeStr, ts.Name.Name, expectedAcronym),
							fmt.Sprintf("Rename struct field '%s' to '%s %s'.", name.Name, expectedAcronym, typeStr),
						)
					}
				}
			}

			// Repository fields in any non-Service internal struct must not be exported
			if isRepositoryType(typeStr) {
				for _, name := range field.Names {
					if unicode.IsUpper(rune(name.Name[0])) {
						unexportedName := deriveUnexportedName(name.Name)
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Dependencies",
							"Repository fields on structs must be unexported; direct external access to repository struct fields is forbidden.",
							fmt.Sprintf("Repository field '%s' on struct '%s' is exported.", name.Name, ts.Name.Name),
							fmt.Sprintf("Make field unexported (e.g. '%s') and expose via getter method 'Get%s() %s'.", unexportedName, name.Name, typeStr),
						)
					}
				}
			}
		}
	}

	// Check Empty Response Structs in endpoint handlers
	if isEndpointDir && strings.HasSuffix(ts.Name.Name, "Response") {
		if len(st.Fields.List) == 0 {
			v.addViolation(
				pos,
				"HTTP Handlers",
				"Handlers returning no data return hextransport.NewSuccessResponse().ToJSON(c) without arguments; never define empty response structs.",
				fmt.Sprintf("Empty response struct '%s' with 0 fields is forbidden.", ts.Name.Name),
				fmt.Sprintf("Delete struct '%s' and return 'hextransport.NewSuccessResponse().ToJSON(c)' without arguments in handler.", ts.Name.Name),
			)
		}
	}

	// Check forbidden oneof= in request struct tags
	if isEndpointDir && strings.HasSuffix(ts.Name.Name, "Request") {
		for _, field := range st.Fields.List {
			if field.Tag != nil {
				tagStr := field.Tag.Value
				if strings.Contains(tagStr, "oneof=") || strings.Contains(tagStr, "oneof =") {
					fieldName := ""
					if len(field.Names) > 0 {
						fieldName = field.Names[0].Name
					}
					v.addViolation(
						v.fset.Position(field.Pos()),
						"Validation",
						"Hardcoding enum values with 'oneof=...' in validator tags is forbidden. Use a typed domain enum implementing hexports.Validatable (IsValid() bool); the framework validator autodetects it automatically.",
						fmt.Sprintf("Field '%s' in struct '%s' uses forbidden hardcoded validation tag 'oneof='.", fieldName, ts.Name.Name),
						"Remove 'oneof=...' from tag and use a typed domain enum implementing IsValid() bool. The framework validator will autodetect and validate it.",
					)
				}
			}
		}
	}
}

func (v *Verifier) checkFuncDecl(filePath string, fn *ast.FuncDecl, isInternal, isServiceDir, isEndpointDir, isPortsDomain bool) {
	pos := v.fset.Position(fn.Pos())

	// Check if this method implements IsValid() bool for an enum type
	if fn.Name.Name == "IsValid" && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		recvType = strings.TrimPrefix(recvType, "*")
		if fn.Type.Params == nil || len(fn.Type.Params.List) == 0 {
			if fn.Type.Results != nil && len(fn.Type.Results.List) == 1 {
				if formatTypeExpr(fn.Type.Results.List[0].Type) == "bool" {
					v.portsEnumMethods[recvType] = true
					if fn.Body != nil {
						if v.portsEnumHandledValues[recvType] == nil {
							v.portsEnumHandledValues[recvType] = make(map[string]bool)
						}
						ast.Inspect(fn.Body, func(n ast.Node) bool {
							if id, ok := n.(*ast.Ident); ok {
								v.portsEnumHandledValues[recvType][id.Name] = true
							}
							return true
						})
					}
				}
			}
		}
	}

	// Check Service constructor
	if isServiceDir && fn.Name.Name == "NewService" && fn.Type.Params != nil {
		repoCount := 0
		for _, param := range fn.Type.Params.List {
			typeStr := formatTypeExpr(param.Type)
			if strings.Contains(typeStr, "TransactionRunner") {
				v.addViolation(
					pos,
					"Tx Runner",
					"Never pass TransactionRunner directly through service constructors; access it via ServiceContext/ServiceBase.",
					"Passing TransactionRunner to NewService constructor is forbidden.",
					"Remove TransactionRunner parameter from NewService(...); call s.GetTransactionRunner().Run(...) via base service.",
				)
			}
			if isRepositoryType(typeStr) {
				repoCount++
				for _, name := range param.Names {
					if name.Name != "repository" {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Service Struct",
							"In NewService constructor, the primary repository parameter MUST be named 'repository'.",
							fmt.Sprintf("Primary repository parameter is named '%s' instead of 'repository'.", name.Name),
							fmt.Sprintf("Rename parameter '%s' to 'repository %s'.", name.Name, typeStr),
						)
					}
				}
			}
			if isSiblingServiceType(typeStr) {
				expectedAcronym := computeAcronym(typeStr)
				for _, name := range param.Names {
					if !isValidServiceFieldName(name.Name, typeStr) {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Sibling Services",
							"In NewService constructor, sibling service parameters MUST be named by strict lowercase acronyms of their interface type.",
							fmt.Sprintf("Sibling service parameter '%s' of type '%s' does not use expected acronym '%s'.", name.Name, typeStr, expectedAcronym),
							fmt.Sprintf("Rename parameter '%s' to '%s %s'.", name.Name, expectedAcronym, typeStr),
						)
					}
				}
			}
		}
		if repoCount > 1 {
			v.addViolation(
				pos,
				"Service Struct",
				"A service must ONLY hold its own repository. Never inject another service's repository directly.",
				"Injecting foreign repositories into NewService constructor is forbidden.",
				"Inject the sibling service interface instead of another domain's repository.",
			)
		}
	}

	// Check setter injection on Service (With...)
	if isServiceDir && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		if strings.Contains(recvType, "Service") && strings.HasPrefix(fn.Name.Name, "With") {
			v.addViolation(
				pos,
				"Service Struct",
				"Cyclic dependencies and setter injection workarounds (With...) are strictly prohibited.",
				fmt.Sprintf("Setter injection method '%s' is forbidden on service struct.", fn.Name.Name),
				"Inject all dependencies via constructor NewService(...). Extract shared logic into an orchestrator service if needed.",
			)
		}
	}

	// Check exported handler methods on Handler structs
	if isEndpointDir && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		if strings.HasSuffix(recvType, "Handler") && fn.Type.Params != nil {
			// Check if method takes fiber.Ctx
			for _, param := range fn.Type.Params.List {
				paramType := formatTypeExpr(param.Type)
				if strings.Contains(paramType, "Ctx") {
					if !ast.IsExported(fn.Name.Name) && fn.Name.Name != "Register" {
						exportedName := deriveExportedName(fn.Name.Name)
						v.addViolation(
							pos,
							"HTTP Handlers",
							"All handler methods MUST be exported with capitalized names: (h <Service>Handler) <MethodName>(c fiber.Ctx) error.",
							fmt.Sprintf("Handler method '%s' is unexported (starts with lowercase).", fn.Name.Name),
							fmt.Sprintf("Capitalize the method name: change '%s' to '%s(c fiber.Ctx) error'.", fn.Name.Name, exportedName),
						)
					}
					break
				}
			}
		}
	}

	// Check CollectionName singular snake_case in domain.go
	if isPortsDomain && fn.Name.Name == "CollectionName" && fn.Body != nil {
		for _, stmt := range fn.Body.List {
			retStmt, ok := stmt.(*ast.ReturnStmt)
			if !ok || len(retStmt.Results) == 0 {
				continue
			}
			lit, isLit := retStmt.Results[0].(*ast.BasicLit)
			if !isLit || lit.Kind != token.STRING {
				continue
			}
			name := strings.Trim(lit.Value, `"`)
			if isPluralCollection(name) {
				v.addViolation(
					pos,
					"Collections",
					"Mongo collection names are singular snake_case (e.g. 'user', 'subscription_tier').",
					fmt.Sprintf("Collection name '%s' appears to be plural.", name),
					fmt.Sprintf("Change collection name to singular snake_case (e.g. '%s').", strings.TrimSuffix(name, "s")),
				)
			}
		}
	}

	// Dynamic time.Now() check: per-function analysis instead of directory flags.
	if isInternal && fn.Body != nil {
		v.checkTimeNow(filePath, fn)
	}
}

func isTimeNowCall(call *ast.CallExpr) bool {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	ident, ok := sel.X.(*ast.Ident)
	return ok && ident.Name == "time" && sel.Sel.Name == "Now"
}

func funcHasTimeParam(fn *ast.FuncDecl) bool {
	if fn.Type.Params == nil {
		return false
	}
	for _, param := range fn.Type.Params.List {
		typeStr := formatTypeExpr(param.Type)
		if typeStr == "time.Time" || typeStr == "Time" {
			return true
		}
	}
	return false
}

func (v *Verifier) checkTimeNow(filePath string, fn *ast.FuncDecl) {
	hasTimeParam := funcHasTimeParam(fn)

	var positions []token.Position
	ast.Inspect(fn.Body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if ok && isTimeNowCall(call) {
			positions = append(positions, v.fset.Position(call.Pos()))
		}
		return true
	})

	if len(positions) == 0 {
		return
	}

	if hasTimeParam {
		for _, pos := range positions {
			v.addViolation(
				pos,
				"Time Handling",
				"Function already receives 'time.Time' as a parameter; use that value instead of calling time.Now().",
				"Calling time.Now() when the function already has a time.Time parameter is forbidden.",
				"Use the existing time parameter (e.g. 'at') instead of calling time.Now().",
			)
		}
		return
	}

	if len(positions) > 1 {
		for _, pos := range positions[1:] {
			v.addViolation(
				pos,
				"Time Handling",
				"Capture time once per function (e.g. 'at := time.Now()') and reuse; avoid multiple time.Now() calls.",
				"Multiple time.Now() calls in the same function. Capture once and reuse.",
				"Replace scattered time.Now() calls with a single 'at := time.Now()' at the start of the function and pass 'at' through.",
			)
		}
	}
}

type structFieldInfo struct {
	name       string
	pos        token.Pos
	exported   bool
	isFunc     bool // field type is func(...)
	isLocalPtr bool // field type is *LocalType (same package, no qualifier)
	typeStr    string
}

// collectStructFields returns a map of struct type name → all named fields
// (exported and unexported). Embedded/anonymous fields are excluded.
func collectStructFields(f *ast.File) map[string][]structFieldInfo {
	result := make(map[string][]structFieldInfo)
	ast.Inspect(f, func(n ast.Node) bool {
		ts, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}
		st, ok := ts.Type.(*ast.StructType)
		if !ok || st.Fields == nil {
			return true
		}
		typeName := ts.Name.Name
		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				continue // embedded/anonymous field — skip
			}
			_, isFunc := field.Type.(*ast.FuncType)
			isLocalPtr := false
			if star, ok := field.Type.(*ast.StarExpr); ok {
				// *LocalType: inner is Ident (same package), not SelectorExpr (other package)
				_, isLocalPtr = star.X.(*ast.Ident)
			}
			typeStr := formatTypeExpr(field.Type)
			if isFunc {
				typeStr = "func(...)"
			}
			for _, name := range field.Names {
				result[typeName] = append(result[typeName], structFieldInfo{
					name:       name.Name,
					pos:        name.Pos(),
					exported:   ast.IsExported(name.Name),
					isFunc:     isFunc,
					isLocalPtr: isLocalPtr,
					typeStr:    typeStr,
				})
			}
		}
		return true
	})
	return result
}

// collectGetterMethods returns a set of struct type names that have at least one
// Get...() method with a return value and no parameters (beyond the receiver).
func collectGetterMethods(f *ast.File) map[string]bool {
	result := make(map[string]bool)
	ast.Inspect(f, func(n ast.Node) bool {
		fn, ok := n.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || len(fn.Recv.List) == 0 {
			return true
		}
		name := fn.Name.Name
		if !strings.HasPrefix(name, "Get") || name == "Get" {
			return true
		}
		if fn.Type.Results == nil || len(fn.Type.Results.List) == 0 {
			return true
		}
		if fn.Type.Params != nil && len(fn.Type.Params.List) > 0 {
			return true
		}
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		recvType = strings.TrimPrefix(recvType, "*")
		result[recvType] = true
		return true
	})
	return result
}

func (v *Verifier) checkStructAccessorConsistency(filePath string, structFields map[string][]structFieldInfo, structGetters map[string]bool) {
	for typeName, fields := range structFields {
		if !structGetters[typeName] {
			continue // no getters → pure data struct, skip
		}
		for _, f := range fields {
			pos := v.fset.Position(f.pos)

			// Rule 1: exported fields bypass the accessor pattern
			if f.exported {
				v.addViolation(
					pos,
					"Struct Accessor Consistency",
					"Structs with getter methods must not have exported fields; all fields should be unexported and accessed via getters.",
					fmt.Sprintf(
						"Exported field '%s' on struct '%s' which has getter methods. Direct field access bypasses the accessor pattern.",
						f.name, typeName,
					),
					fmt.Sprintf(
						"Make field '%s' unexported and add a 'Get%s()' method if callers need access outside the package.",
						f.name, f.name,
					),
				)
			}

			// Rule 2: func-type fields violate interface injection
			if f.isFunc {
				v.addViolation(
					pos,
					"Struct Accessor Consistency",
					"Function-type fields in dependency structs must be replaced with interface injection; define the behavior as an interface in internal/ports.",
					fmt.Sprintf(
						"Field '%s %s' on struct '%s' is a raw function type. Raw function fields cannot be versioned, mocked, or described by a port interface.",
						f.name, f.typeStr, typeName,
					),
					fmt.Sprintf(
						"Extract '%s' into an interface (e.g. ports.%sHandler) and inject it via the struct's constructor or a getter method.",
						f.name, f.name,
					),
				)
			}

			// Rule 3: concrete local pointer fields (not interface, not from ports)
			if f.isLocalPtr {
				v.addViolation(
					pos,
					"Struct Accessor Consistency",
					"Concrete pointer fields in dependency structs must be replaced with interface injection; define the abstraction in internal/ports.",
					fmt.Sprintf(
						"Field '%s %s' on struct '%s' is a concrete pointer to a local type, not an interface. This couples the struct to a concrete implementation.",
						f.name, f.typeStr, typeName,
					),
					fmt.Sprintf(
						"Define an interface for '%s' in internal/ports and inject the interface instead of the concrete pointer '%s'.",
						f.typeStr, f.typeStr,
					),
				)
			}
		}
	}
}


func (v *Verifier) checkCallExpr(filePath string, call *ast.CallExpr, isInternal, isServiceDir, isEndpointDir, isDatabaseDir bool, importedPackages map[string]bool) {
	pos := v.fset.Position(call.Pos())

	// time.Now() is checked per-function in checkTimeNow, not per-call here.

	// Check c.Query(...) in endpoint handlers
	if isEndpointDir {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Query" {
			v.addViolation(
				pos,
				"HTTP Queries",
				"Bind request DTOs via hextransport.Bind(c, &req) or hextransport.BindQuery(c, &req); never manually parse query parameters with c.Query().",
				"Direct query parameter access with c.Query(...) is forbidden.",
				"Define a request query struct (with `query:\"...\"` tags) and bind via 'hextransport.BindQuery(c, &req)'.",
			)
		}
	}

	// Check hardcoded db.Collection("...") in database repositories
	if isDatabaseDir {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Collection" && len(call.Args) > 0 {
			if lit, ok := call.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
				v.addViolation(
					pos,
					"Collections",
					"Always obtain collection names via ports.<Entity>Model{}.CollectionName(); never hardcode collection name strings.",
					fmt.Sprintf("Hardcoded collection name string %s is forbidden in db.Collection(...).", lit.Value),
					fmt.Sprintf("Replace %s with ports.<Entity>Model{}.CollectionName().", lit.Value),
				)
			}
		}
	}

	// Check abbreviated getter method calls (e.g. .GetConnectionRepo())
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		if ident, ok := sel.X.(*ast.Ident); ok && importedPackages[ident.Name] {
			return
		}
		name := sel.Sel.Name
		if strings.HasPrefix(name, "Get") && strings.HasSuffix(name, "Repo") {
			correctGetter := deriveGetterName(name)
			v.addViolation(
				pos,
				"Dependencies",
				"Interface-based dependencies use full-word getter methods; never use shortened abbreviations (e.g. GetConnectionRepository(), not GetConnectionRepo()).",
				fmt.Sprintf("Abbreviated getter method call '%s()' is forbidden.", name),
				fmt.Sprintf("Call full method name '%s' instead.", correctGetter),
			)
		} else if strings.HasSuffix(name, "Repository") && !strings.HasPrefix(name, "Get") && !strings.HasPrefix(name, "New") {
			v.addViolation(
				pos,
				"Dependencies",
				"Interface-based dependencies use full-word getter methods starting with 'Get' (e.g. GetConnectionRepository()).",
				fmt.Sprintf("Getter method call '%s()' must start with 'Get'.", name),
				fmt.Sprintf("Call 'Get%s()' instead.", name),
			)
		}
	}
}

func (v *Verifier) checkBinaryExpr(filePath string, bin *ast.BinaryExpr, isInternal, isServiceDir bool) {
	pos := v.fset.Position(bin.Pos())

	// Check sentinel equality: err == ports.ErrNotFound or err != ports.ErrNotFound
	if bin.Op == token.EQL || bin.Op == token.NEQ {
		leftStr := exprToString(bin.X)
		rightStr := exprToString(bin.Y)

		if !isNilExpr(bin.X) && !isNilExpr(bin.Y) && (isErrSentinel(leftStr) || isErrSentinel(rightStr)) {
			opStr := "=="
			if bin.Op == token.NEQ {
				opStr = "!="
			}
			sentinel := getSentinelExpr(leftStr, rightStr)
			v.addViolation(
				pos,
				"Sentinels",
				"Compare sentinels only with errors.Is(err, ports.ErrX); never ==, !=, or switch err.",
				fmt.Sprintf("Direct sentinel comparison '%s %s %s' is forbidden.", leftStr, opStr, rightStr),
				fmt.Sprintf("Replace direct comparison with 'errors.Is(err, %s)'.", sentinel),
			)
		}

		// Check nil checks on injected dependencies: if s.us == nil, if t.brr != nil
		if isInternal {
			var depExpr ast.Expr
			if isNilExpr(bin.X) && isDependencyExpr(bin.Y) {
				depExpr = bin.Y
			} else if isNilExpr(bin.Y) && isDependencyExpr(bin.X) {
				depExpr = bin.X
			}

			if depExpr != nil {
				depStr := exprToString(depExpr)
				if isServiceSelector(depExpr) && isServiceDir {
					v.addViolation(
						pos,
						"Sibling Services",
						"Injected service interfaces are NEVER nil. Never write nil checks (if s.us != nil).",
						fmt.Sprintf("Nil check on injected sibling service '%s' is forbidden.", depStr),
						fmt.Sprintf("Remove nil check guard on '%s'. Dependencies are guaranteed non-nil via constructor NewService(...).", depStr),
					)
				} else {
					v.addViolation(
						pos,
						"Dependencies",
						"Injected dependencies are NEVER nil. Never write nil checks (e.g. 'if s.us != nil' or 'if t.brr != nil'). Dependencies must be injected unconditionally via constructors.",
						fmt.Sprintf("Nil check on injected dependency '%s' is forbidden.", depStr),
						fmt.Sprintf("Remove nil check guard on '%s'. Dependencies are guaranteed non-nil via constructor injection.", depStr),
					)
				}
			}
		}
	}
}

func (v *Verifier) checkAssignStmt(filePath string, assign *ast.AssignStmt, isInternal bool) {
	if !isInternal {
		return
	}
	pos := v.fset.Position(assign.Pos())

	// 1. Explicit error suppression on variable: _ = err, _ = serr, etc.
	if len(assign.Lhs) == len(assign.Rhs) {
		for i, lhs := range assign.Lhs {
			if isBlankIdent(lhs) {
				if ident, ok := assign.Rhs[i].(*ast.Ident); ok {
					lower := strings.ToLower(ident.Name)
					if lower == "err" || lower == "serr" || strings.HasSuffix(lower, "err") || strings.HasSuffix(lower, "error") {
						v.addViolation(
							pos,
							"Errors",
							"Suppressing errors with '_ = err' is forbidden; every error must be handled or returned wrapped.",
							fmt.Sprintf("Discarding error '%s' with blank identifier is forbidden.", ident.Name),
							"Handle the error or return it wrapped with 'errors.Wrap(err, \"context message\")'.",
						)
						return
					}
				}
			}
		}
	}

	// 2. Discarding error from dependency method call:
	// e.g.: _ = t.brr.UpdateStats(...), _, _ = s.repository.UpdateEarnCounters(...)
	// In hexagonal architecture, all dependency methods return error as their last return value.
	// Discarding the last return value with '_' suppresses the error.
	if len(assign.Lhs) > 0 && isBlankIdent(assign.Lhs[len(assign.Lhs)-1]) && len(assign.Rhs) == 1 {
		if call, ok := assign.Rhs[0].(*ast.CallExpr); ok {
			if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
				if isDependencyExpr(sel.X) || isDepsExpr(sel.X) {
					callStr := exprToString(call)
					v.addViolation(
						pos,
						"Errors",
						"Suppressing errors from dependency method calls with blank identifier '_' is forbidden; every error must be handled or returned wrapped.",
						fmt.Sprintf("Discarding error return from dependency call '%s' is forbidden.", callStr),
						"Handle the returned error or return it wrapped with 'errors.Wrap(err, \"context message\")'.",
					)
					return
				}
			}
		}
	}
}

func (v *Verifier) checkSwitchStmt(filePath string, sw *ast.SwitchStmt) {
	if sw.Tag == nil {
		return
	}
	tagStr := exprToString(sw.Tag)
	if tagStr == "err" || strings.HasSuffix(tagStr, "Err") || strings.HasSuffix(tagStr, "Error") {
		for _, stmt := range sw.Body.List {
			if cc, ok := stmt.(*ast.CaseClause); ok {
				for _, expr := range cc.List {
					exprStr := exprToString(expr)
					if isErrSentinel(exprStr) {
						v.addViolation(
							v.fset.Position(expr.Pos()),
							"Sentinels",
							"Compare sentinels only with errors.Is(err, ports.ErrX); never switch err.",
							fmt.Sprintf("Switch case on error sentinel '%s' is forbidden.", exprStr),
							fmt.Sprintf("Replace switch with 'if errors.Is(err, %s)' checks.", exprStr),
						)
					}
				}
			}
		}
	}
}

func isDepsExpr(expr ast.Expr) bool {
	switch e := expr.(type) {
	case *ast.Ident:
		return strings.EqualFold(e.Name, "deps")
	case *ast.SelectorExpr:
		return strings.EqualFold(e.Sel.Name, "deps")
	default:
		return false
	}
}

func (v *Verifier) checkSelectorExpr(filePath string, sel *ast.SelectorExpr, importedPackages map[string]bool, isCallFun bool, isTypeExpr bool) {
	if isTypeExpr {
		return
	}

	// Ignore package selectors like repo.SomeFunc, ports.UserRepository, time.Now
	if ident, ok := sel.X.(*ast.Ident); ok && importedPackages[ident.Name] {
		return
	}

	name := sel.Sel.Name

	// 1. Check direct struct field access to *Repo: s.deps.ConnectionRepo, deps.ConnectionRepo, d.stateRepo
	if strings.HasSuffix(name, "Repo") && name != "repo" && !strings.HasPrefix(name, "Get") {
		correctGetter := deriveGetterName(name)
		if isDepsExpr(sel.X) || unicode.IsUpper(rune(name[0])) {
			v.addViolation(
				v.fset.Position(sel.Pos()),
				"Dependencies",
				"Interface-based dependencies use full-word getter methods; direct struct field accesses or abbreviations like '*Repo' are forbidden.",
				fmt.Sprintf("Direct field access or abbreviated name '%s' is forbidden.", name),
				fmt.Sprintf("Call getter method '%s' instead of accessing field '%s'.", correctGetter, name),
			)
		} else {
			// Private struct field on receiver (e.g. d.stateRepo)
			v.addViolation(
				v.fset.Position(sel.Pos()),
				"Dependencies",
				"Interface-based dependencies use full-word getter methods; direct struct field accesses or abbreviations like '*Repo' are forbidden.",
				fmt.Sprintf("Direct field access or abbreviated name '%s' is forbidden.", name),
				fmt.Sprintf("Rename abbreviated field '%s' to full name '%s' or acronym, or call getter method '%s'.", name, deriveFullRepoName(name), correctGetter),
			)
		}
		return
	}

	// 2. Check direct struct field access to *Repository: s.deps.ConnectionRepository or deps.ConnectionRepository
	if strings.HasSuffix(name, "Repository") && name != "repository" && !strings.HasPrefix(name, "Get") {
		correctGetter := deriveGetterName(name)
		v.addViolation(
			v.fset.Position(sel.Pos()),
			"Dependencies",
			"Interface-based dependencies use full-word getter methods; direct struct field access to repository fields is forbidden.",
			fmt.Sprintf("Direct struct field access to repository '%s' is forbidden.", name),
			fmt.Sprintf("Call getter method '%s' instead of accessing field '%s'.", correctGetter, name),
		)
		return
	}

	// 3. Check direct struct field access to *Service (not called as a function): s.deps.CreditService, deps.AccountService, h.connectionService
	// Framework queueService is excluded as it is not a sibling domain service.
	if !isCallFun && strings.HasSuffix(name, "Service") && !strings.HasPrefix(name, "Get") && name != "queueService" && name != "QueueService" && name != "Service" {
		v.addViolation(
			v.fset.Position(sel.Pos()),
			"Sibling Services",
			"Injected sibling services must be stored in unexported acronym fields (e.g. 's.cs') on service structs or accessed via getter methods (e.g. 'GetCreditService()'); direct struct field access to service full names is forbidden.",
			fmt.Sprintf("Direct struct field access to service '%s' is forbidden.", name),
			fmt.Sprintf("Store the service in an unexported acronym field (e.g. 'cs') or call getter method 'Get%s()'.", deriveExportedName(name)),
		)
		return
	}
}

func (v *Verifier) checkValueSpec(filePath string, vs *ast.ValueSpec) {
	// Check for CollectionName = "..." constant or variable
	for _, name := range vs.Names {
		if name.Name == "CollectionName" {
			v.addViolation(
				v.fset.Position(name.Pos()),
				"Collections",
				"Collection names must be obtained from model's CollectionName() method, not string constants.",
				"Defining 'CollectionName' as a string constant or variable is forbidden.",
				"Implement 'func (m <Entity>Model) CollectionName() string' on the model struct.",
			)
		}
	}
}

// Helpers

func deriveGetterName(name string) string {
	if strings.HasPrefix(name, "Get") && strings.HasSuffix(name, "Repo") {
		base := strings.TrimPrefix(name, "Get")
		base = strings.TrimSuffix(base, "Repo")
		if strings.EqualFold(base, "conn") {
			base = "Connection"
		}
		return "Get" + deriveExportedName(base) + "Repository()"
	}
	if strings.HasSuffix(name, "Repo") {
		base := strings.TrimSuffix(name, "Repo")
		if strings.EqualFold(base, "conn") {
			base = "Connection"
		}
		return "Get" + deriveExportedName(base) + "Repository()"
	}
	if strings.HasSuffix(name, "Repository") {
		return "Get" + deriveExportedName(name) + "()"
	}
	return "Get" + deriveExportedName(name) + "()"
}

func deriveFullRepoName(name string) string {
	base := strings.TrimSuffix(name, "Repo")
	if strings.EqualFold(base, "conn") {
		return "connectionRepository"
	}
	return deriveUnexportedName(base) + "Repository"
}

func deriveUnexportedName(name string) string {
	if name == "" {
		return ""
	}
	r := []rune(name)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func deriveExportedName(name string) string {
	if name == "" {
		return ""
	}
	r := []rune(name)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func deriveSentinelName(name string) string {
	if strings.HasPrefix(name, "err") {
		return "Err" + strings.TrimPrefix(name, "err")
	}
	return deriveExportedName(name)
}

func isErrorCreationCall(call *ast.CallExpr) bool {
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		if ident, ok := sel.X.(*ast.Ident); ok {
			if ident.Name == "errors" && (sel.Sel.Name == "New" || sel.Sel.Name == "Errorf") {
				return true
			}
			if ident.Name == "fmt" && sel.Sel.Name == "Errorf" {
				return true
			}
			if ident.Name == "serviceerrors" && strings.HasPrefix(sel.Sel.Name, "NewServiceError") {
				return true
			}
		}
	}
	return false
}


func formatTypeExpr(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return formatTypeExpr(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + formatTypeExpr(t.X)
	default:
		return ""
	}
}

func markTypeSelectors(expr ast.Expr, m map[*ast.SelectorExpr]bool) {
	if expr == nil {
		return
	}
	ast.Inspect(expr, func(n ast.Node) bool {
		if sel, ok := n.(*ast.SelectorExpr); ok {
			m[sel] = true
		}
		return true
	})
}

func isRepositoryType(typeStr string) bool {
	clean := strings.TrimPrefix(typeStr, "*")
	if !strings.HasSuffix(clean, "Repository") || strings.Contains(clean, "QueueRepository") {
		return false
	}
	parts := strings.Split(clean, ".")
	leaf := parts[len(parts)-1]
	if leaf == "Repository" {
		return false
	}
	if len(parts) > 1 {
		return parts[0] == "ports"
	}
	return true
}

func isSiblingServiceType(typeStr string) bool {
	if strings.HasPrefix(typeStr, "*") {
		return false
	}
	if !strings.HasSuffix(typeStr, "Service") ||
		strings.Contains(typeStr, "ServiceBase") ||
		strings.Contains(typeStr, "QueueService") {
		return false
	}
	parts := strings.Split(typeStr, ".")
	leaf := parts[len(parts)-1]
	if leaf == "Service" {
		return false
	}
	// If qualified with a package, sibling services MUST come from ports package (e.g. ports.UserService)
	if len(parts) > 1 {
		return parts[0] == "ports"
	}
	return true
}

func computeAcronym(typeStr string) string {
	parts := strings.Split(typeStr, ".")
	leaf := parts[len(parts)-1]
	leaf = strings.TrimPrefix(leaf, "*")

	var letters []rune
	for _, r := range leaf {
		if unicode.IsUpper(r) {
			letters = append(letters, unicode.ToLower(r))
		}
	}
	return string(letters)
}

func isErrSentinel(str string) bool {
	if strings.HasSuffix(str, ")") || strings.HasSuffix(str, "(...)") {
		return false
	}
	if strings.HasPrefix(str, "ports.Err") {
		return true
	}
	if strings.HasPrefix(str, "Err") && str != "Error" {
		return true
	}
	if strings.Contains(str, ".Err") {
		idx := strings.Index(str, ".Err")
		after := str[idx+4:]
		if after == "or" || strings.HasPrefix(after, "or.") {
			return false
		}
		return true
	}
	return false
}

func getSentinelExpr(left, right string) string {
	if isErrSentinel(left) {
		return left
	}
	return right
}

func isNilExpr(expr ast.Expr) bool {
	if ident, ok := expr.(*ast.Ident); ok && ident.Name == "nil" {
		return true
	}
	return false
}

func isServiceSelector(expr ast.Expr) bool {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	fieldName := sel.Sel.Name
	if fieldName == "repository" || fieldName == "ServiceBase" || fieldName == "ctx" {
		return false
	}
	return isServiceAcronym(fieldName)
}

func isServiceAcronym(str string) bool {
	// e.g. us, cs, bcs, abcs, userService
	clean := str
	if idx := strings.LastIndex(str, "."); idx != -1 {
		clean = str[idx+1:]
	}
	if clean == "err" || clean == "ctx" || clean == "nil" || clean == "ok" {
		return false
	}
	if strings.HasSuffix(clean, "Service") || strings.HasSuffix(clean, "Svc") {
		return true
	}
	// 2 to 4 lowercase letters, e.g. "us", "cs", "bcs", "abcs"
	if len(clean) >= 2 && len(clean) <= 4 {
		for _, r := range clean {
			if !unicode.IsLower(r) {
				return false
			}
		}
		return true
	}
	return false
}

func isValidServiceFieldName(name, typeStr string) bool {
	if name == "" {
		return false
	}
	// Must not be exported
	if unicode.IsUpper(rune(name[0])) {
		return false
	}
	// Must not use full name or suffix "Service" or "Svc"
	if strings.HasSuffix(name, "Service") || strings.HasSuffix(name, "Svc") {
		return false
	}
	// Must be 2 to 4 lowercase letters
	if len(name) < 2 || len(name) > 4 {
		return false
	}
	for _, r := range name {
		if !unicode.IsLower(r) {
			return false
		}
	}
	// All service acronyms end in 's'
	if name[len(name)-1] != 's' {
		return false
	}
	cleanType := typeStr
	if idx := strings.LastIndex(cleanType, "."); idx != -1 {
		cleanType = cleanType[idx+1:]
	}
	cleanType = strings.TrimPrefix(cleanType, "*")
	return isSubsequence(name, cleanType)
}

func isSubsequence(sub, str string) bool {
	sub = strings.ToLower(sub)
	str = strings.ToLower(str)
	subIdx := 0
	for i := 0; i < len(str) && subIdx < len(sub); i++ {
		if str[i] == sub[subIdx] {
			subIdx++
		}
	}
	return subIdx == len(sub)
}

func isBlankIdent(expr ast.Expr) bool {
	if ident, ok := expr.(*ast.Ident); ok && ident.Name == "_" {
		return true
	}
	return false
}

func isDependencyExpr(expr ast.Expr) bool {
	if expr == nil {
		return false
	}
	switch e := expr.(type) {
	case *ast.SelectorExpr:
		if isDepsExpr(e.X) {
			return true
		}
		return isDependencyName(e.Sel.Name)
	case *ast.CallExpr:
		if sel, ok := e.Fun.(*ast.SelectorExpr); ok {
			return isDependencyName(sel.Sel.Name)
		}
		return false
	case *ast.Ident:
		return isDependencyName(e.Name)
	default:
		return false
	}
}

func isDependencyName(name string) bool {
	lower := strings.ToLower(name)
	if strings.HasSuffix(lower, "err") || strings.HasSuffix(lower, "error") {
		return false
	}
	if lower == "repository" || lower == "repo" {
		return true
	}
	if strings.HasSuffix(lower, "repository") || strings.HasSuffix(lower, "repo") {
		return true
	}
	if strings.HasSuffix(lower, "service") || strings.HasSuffix(lower, "svc") {
		return true
	}
	if strings.HasSuffix(lower, "client") {
		return true
	}
	if strings.HasSuffix(lower, "registry") {
		return true
	}
	if strings.HasSuffix(lower, "dialer") {
		return true
	}
	if strings.HasSuffix(lower, "handshaker") {
		return true
	}
	if strings.HasSuffix(lower, "supervisor") {
		return true
	}
	if strings.HasSuffix(lower, "runner") {
		return true
	}
	if strings.HasSuffix(lower, "eventbus") || lower == "eventbus" || lower == "bus" {
		return true
	}
	return isDependencyAcronym(name)
}

func isDependencyAcronym(name string) bool {
	clean := name
	if idx := strings.LastIndex(name, "."); idx != -1 {
		clean = name[idx+1:]
	}
	if len(clean) < 2 || len(clean) > 4 {
		return false
	}
	lower := strings.ToLower(clean)
	if strings.HasSuffix(lower, "err") || strings.HasSuffix(lower, "error") {
		return false
	}
	for _, r := range clean {
		if !unicode.IsLower(r) {
			return false
		}
	}
	// Acronyms end in 'r' (repository), 's' (service), 'c' (client)
	last := clean[len(clean)-1]
	if last != 'r' && last != 's' && last != 'c' {
		return false
	}
	// Exclude common non-acronym words
	switch clean {
	case "user", "char", "tier", "pair", "hour", "year", "door", "peer",
		"attr", "expr", "curr", "iter", "ptr", "str", "bar", "car",
		"this", "status", "pass", "plus", "loss", "desc", "spec", "sync",
		"func", "exec", "proc", "calc", "misc", "doc", "src", "pic", "rec",
		"args", "rows", "keys", "tags", "opts", "vars", "msgs", "body":
		return false
	}
	return true
}

func isPluralCollection(name string) bool {
	if !strings.HasSuffix(name, "s") {
		return false
	}
	singularExceptions := map[string]bool{
		"status":   true,
		"address":  true,
		"access":   true,
		"process":  true,
		"bus":      true,
		"class":    true,
		"lens":     true,
		"basis":    true,
		"analysis": true,
		"canvas":   true,
		"compass":  true,
		"crisis":   true,
		"alias":    true,
		"bonus":    true,
		"news":     true,
		"series":   true,
		"species":  true,
	}
	return !singularExceptions[name]
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.CallExpr:
		return exprToString(e.Fun) + "(...)"
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.BasicLit:
		return e.Value
	default:
		return ""
	}
}

func (v *Verifier) checkFinalInvariants() {
	if v.invariantsChecked {
		return
	}
	v.invariantsChecked = true

	for typeName, pos := range v.portsEnumTypes {
		if !v.portsEnumMethods[typeName] {
			v.addViolation(
				pos,
				"Enums",
				"All domain enums defined in internal/ports MUST implement 'IsValid() bool' (implementing hexports.Validatable).",
				fmt.Sprintf("Domain enum type '%s' does not implement 'IsValid() bool'.", typeName),
				fmt.Sprintf("Implement 'func (e %s) IsValid() bool' with a switch statement covering all declared %s constants.", typeName, typeName),
			)
			continue
		}

		handled := v.portsEnumHandledValues[typeName]
		for _, constant := range v.portsEnumConstants[typeName] {
			if !handled[constant.name] {
				v.addViolation(
					constant.pos,
					"Enums",
					fmt.Sprintf("The 'IsValid() bool' method on domain enum '%s' must handle all declared constants.", typeName),
					fmt.Sprintf("Enum constant '%s' of type '%s' is not checked in 'IsValid()'.", constant.name, typeName),
					fmt.Sprintf("Add '%s' to the switch statement in 'func (e %s) IsValid() bool'.", constant.name, typeName),
				)
			}
		}
	}
}

func isBuiltinGoType(t string) bool {
	switch t {
	case "string", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128",
		"bool", "byte", "rune", "error", "any",
		"time.Duration", "time.Time":
		return true
	default:
		return false
	}
}
