package rules

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"
)

type Violation struct {
	Pos         token.Position
	Category    string
	Contract    string
	Description string
	Suggestion  string
}

func (v Violation) String() string {
	var sb strings.Builder
	if v.Pos.IsValid() && v.Pos.Filename != "" {
		sb.WriteString(fmt.Sprintf("%s:%d:%d: ", v.Pos.Filename, v.Pos.Line, v.Pos.Column))
	}
	sb.WriteString(fmt.Sprintf("[%s] %s", v.Category, v.Description))
	if v.Suggestion != "" {
		sb.WriteString(fmt.Sprintf(" (Fix: %s)", v.Suggestion))
	}
	return sb.String()
}

func (v Violation) Format(index, total int) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("[%d/%d] ❌ AGENTS.md Rule Violation: %s\n", index, total, v.Category))
	if v.Pos.IsValid() && v.Pos.Filename != "" {
		sb.WriteString(fmt.Sprintf("    Location: %s:%d:%d\n", v.Pos.Filename, v.Pos.Line, v.Pos.Column))
	}
	if v.Contract != "" {
		sb.WriteString(fmt.Sprintf("    Contract: %s\n", v.Contract))
	}
	sb.WriteString(fmt.Sprintf("    Problem:  %s\n", v.Description))
	if v.Suggestion != "" {
		sb.WriteString(fmt.Sprintf("    Fix:      %s\n", v.Suggestion))
	}
	return sb.String()
}

type enumConstant struct {
	name string
	pos  token.Position
}

type Verifier struct {
	fset                   *token.FileSet
	violations             []Violation
	fileCount              int
	portsEnumTypes         map[string]token.Position
	portsEnumMethods       map[string]bool
	portsEnumConstants     map[string][]enumConstant
	portsEnumHandledValues map[string]map[string]bool
	invariantsChecked      bool
}

func NewVerifier() *Verifier {
	return &Verifier{
		fset:                   token.NewFileSet(),
		portsEnumTypes:         make(map[string]token.Position),
		portsEnumMethods:       make(map[string]bool),
		portsEnumConstants:     make(map[string][]enumConstant),
		portsEnumHandledValues: make(map[string]map[string]bool),
	}
}

func (v *Verifier) Violations() []Violation {
	v.checkFinalInvariants()
	return v.violations
}

func (v *Verifier) FileCount() int {
	return v.fileCount
}

func (v *Verifier) addViolation(pos token.Position, category, contract, desc, suggestion string) {
	v.violations = append(v.violations, Violation{
		Pos:         pos,
		Category:    category,
		Contract:    contract,
		Description: desc,
		Suggestion:  suggestion,
	})
}

// VerifyPath scans the root path recursively for Go files and checks all hexag rules.
func (v *Verifier) VerifyPath(root string) error {
	info, err := os.Stat(root)
	if err != nil {
		return fmt.Errorf("failed to stat path %s: %w", root, err)
	}

	if !info.IsDir() {
		if strings.HasSuffix(root, ".go") {
			v.fileCount++
			v.checkFile(root)
		}
		return nil
	}

	return filepath.WalkDir(root, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}

		// Skip VCS, vendor, node_modules, and bin dirs
		if d.IsDir() {
			name := d.Name()
			if name == ".git" || name == "vendor" || name == "node_modules" || name == "bin" {
				return filepath.SkipDir
			}
			return nil
		}

		if strings.HasSuffix(path, ".go") {
			v.fileCount++
			v.checkFile(path)
		}

		return nil
	})
}

func (v *Verifier) checkFile(filePath string) {
	slashPath := filepath.ToSlash(filePath)
	baseName := filepath.Base(filePath)
	isTestFile := strings.HasSuffix(baseName, "_test.go")

	// 1. File Naming Rules (applied to files under internal/)
	if isInternalPath(slashPath) && !isGeneratedPath(slashPath) {
		v.checkFileName(filePath, baseName, isTestFile)
	}

	// Parse file AST
	src, err := os.ReadFile(filePath)
	if err != nil {
		v.addViolation(
			token.Position{Filename: filePath},
			"Parser",
			"Source files must be readable Go code.",
			fmt.Sprintf("Failed to read file: %v", err),
			"Ensure file exists and has read permissions.",
		)
		return
	}

	fileNode, err := parser.ParseFile(v.fset, filePath, src, parser.ParseComments)
	if err != nil {
		v.addViolation(
			token.Position{Filename: filePath},
			"Parser",
			"Source files must compile and be valid Go syntax.",
			fmt.Sprintf("Failed to parse Go file: %v", err),
			"Fix syntax errors so AST parser can parse the file.",
		)
		return
	}

	// Skip AST checks on generated files
	if isGeneratedFile(fileNode) {
		return
	}

	// 2. AST-based Rules
	v.checkAST(filePath, fileNode, isTestFile)
}

func isInternalPath(slashPath string) bool {
	return strings.Contains(slashPath, "/internal/") || strings.HasPrefix(slashPath, "internal/")
}

func isGeneratedPath(slashPath string) bool {
	return strings.Contains(slashPath, "/adapters/database/mongo/models/") ||
		strings.Contains(slashPath, "/ports/mocks/")
}

func isGeneratedFile(f *ast.File) bool {
	for _, commentGroup := range f.Comments {
		for _, comment := range commentGroup.List {
			text := strings.ToLower(comment.Text)
			if strings.Contains(text, "code generated by") && strings.Contains(text, "do not edit") {
				return true
			}
		}
	}
	return false
}

func (v *Verifier) checkFileName(filePath, baseName string, isTestFile bool) {
	pos := token.Position{Filename: filePath, Line: 1, Column: 1}

	// Rule: No uppercase characters in filename
	if baseName != strings.ToLower(baseName) {
		v.addViolation(
			pos,
			"File Names",
			"Filenames must be single-word lowercase.",
			fmt.Sprintf("Filename '%s' contains uppercase characters.", baseName),
			fmt.Sprintf("Rename to lowercase '%s'.", strings.ToLower(baseName)),
		)
	}

	// Rule: No underscores (except the standard Go test suffix '_test.go')
	var prefix string
	if isTestFile {
		prefix = strings.TrimSuffix(baseName, "_test.go")
		if strings.Contains(prefix, "_") {
			kebab := strings.ReplaceAll(prefix, "_", "-") + "_test.go"
			v.addViolation(
				pos,
				"File Names",
				"Single-word lowercase filenames. Sibling disambiguation uses kebab-case.",
				fmt.Sprintf("Test filename '%s' contains forbidden underscore.", baseName),
				fmt.Sprintf("Rename to single-word lowercase or sibling kebab-case ('%s').", kebab),
			)
		}
	} else {
		prefix = strings.TrimSuffix(baseName, ".go")
		if strings.Contains(baseName, "_") {
			kebab := strings.ReplaceAll(baseName, "_", "-")
			v.addViolation(
				pos,
				"File Names",
				"Single-word lowercase filenames. The directory provides the contextual scope.",
				fmt.Sprintf("Filename '%s' contains forbidden underscore.", baseName),
				fmt.Sprintf("Rename to single-word lowercase (e.g. 'service.go', 'handler.go') or sibling kebab-case ('%s').", kebab),
			)
		}
	}

	// Rule: Banned kebab-case with role suffixes
	nameToCheck := prefix + ".go"
	rolePattern := regexp.MustCompile(`-(service|handler|repository|repo|rules|model|models)\.go$`)
	if rolePattern.MatchString(nameToCheck) {
		v.addViolation(
			pos,
			"File Names",
			"The directory provides the contextual scope. Role files must be single-word lowercase.",
			fmt.Sprintf("Filename '%s' uses banned kebab-case with role suffix.", baseName),
			"Remove the domain prefix and name by role directly (e.g. 'service.go', 'handler.go', 'repository.go').",
		)
	}

	// Rule: Banned repo abbreviation in filename
	if strings.HasSuffix(nameToCheck, "repo.go") {
		v.addViolation(
			pos,
			"File Names",
			"Use full words for role files; abbreviations like 'repo' are forbidden.",
			fmt.Sprintf("Filename '%s' uses forbidden abbreviation 'repo'.", baseName),
			"Rename to 'repository.go'.",
		)
	}
}

func (v *Verifier) checkAST(filePath string, f *ast.File, isTestFile bool) {
	slashPath := filepath.ToSlash(filePath)
	isServiceDir := strings.Contains(slashPath, "/services/")
	isEndpointDir := strings.Contains(slashPath, "/adapters/endpoint/")
	isDatabaseDir := strings.Contains(slashPath, "/adapters/database/")
	isPortsDomain := strings.HasSuffix(slashPath, "internal/ports/domain.go")
	isPortsDir := strings.Contains(slashPath, "/internal/ports/") && !strings.Contains(slashPath, "/internal/ports/mocks/")

	importedPackages := make(map[string]bool)
	for _, imp := range f.Imports {
		if imp.Name != nil {
			importedPackages[imp.Name.Name] = true
		} else {
			pathVal := strings.Trim(imp.Path.Value, `"`)
			parts := strings.Split(pathVal, "/")
			importedPackages[parts[len(parts)-1]] = true
		}
	}

	callFunMap := make(map[*ast.SelectorExpr]bool)
	ast.Inspect(f, func(n ast.Node) bool {
		if call, ok := n.(*ast.CallExpr); ok {
			if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
				callFunMap[sel] = true
			}
		}
		return true
	})

	ast.Inspect(f, func(n ast.Node) bool {
		if n == nil {
			return true
		}

		switch node := n.(type) {
		case *ast.GenDecl:
			if isPortsDir && node.Tok == token.CONST {
				lastType := ""
				for _, spec := range node.Specs {
					if vs, ok := spec.(*ast.ValueSpec); ok {
						if vs.Type != nil {
							lastType = formatTypeExpr(vs.Type)
						} else if len(vs.Values) > 0 {
							lastType = ""
						}
						if lastType != "" && !strings.Contains(lastType, ".") && !isBuiltinGoType(lastType) {
							if _, exists := v.portsEnumTypes[lastType]; !exists {
								v.portsEnumTypes[lastType] = v.fset.Position(vs.Pos())
							}
							for _, name := range vs.Names {
								v.portsEnumConstants[lastType] = append(v.portsEnumConstants[lastType], enumConstant{
									name: name.Name,
									pos:  v.fset.Position(name.Pos()),
								})
							}
						}
					}
				}
			}

		case *ast.TypeSpec:
			v.checkTypeSpec(filePath, node, isServiceDir, isEndpointDir, isTestFile)

		case *ast.FuncDecl:
			v.checkFuncDecl(filePath, node, isServiceDir, isEndpointDir, isPortsDomain)

		case *ast.CallExpr:
			v.checkCallExpr(filePath, node, isServiceDir, isEndpointDir, isDatabaseDir, isTestFile, importedPackages)

		case *ast.BinaryExpr:
			v.checkBinaryExpr(filePath, node, isServiceDir)

		case *ast.SwitchStmt:
			v.checkSwitchStmt(filePath, node)

		case *ast.SelectorExpr:
			v.checkSelectorExpr(filePath, node, importedPackages, callFunMap[node], isTestFile)

		case *ast.ValueSpec:
			v.checkValueSpec(filePath, node)
		}

		return true
	})
}

func (v *Verifier) checkTypeSpec(filePath string, ts *ast.TypeSpec, isServiceDir, isEndpointDir, isTestFile bool) {
	pos := v.fset.Position(ts.Pos())
	st, isStruct := ts.Type.(*ast.StructType)
	if !isStruct || st.Fields == nil {
		return
	}

	slashPath := filepath.ToSlash(filePath)
	isInternal := strings.Contains(slashPath, "/internal/") || strings.HasPrefix(slashPath, "internal/")
	isMock := strings.Contains(slashPath, "/internal/ports/mocks/") || strings.Contains(slashPath, "/ports/mocks/")

	// Check Service struct fields
	if isServiceDir && ts.Name.Name == "Service" {
		repoFields := 0

		for _, field := range st.Fields.List {
			typeStr := formatTypeExpr(field.Type)

			// Check for TransactionRunner stored on service struct
			if strings.Contains(typeStr, "TransactionRunner") {
				v.addViolation(
					pos,
					"Tx Runner",
					"Never store TransactionRunner as a field on service structs.",
					"Storing TransactionRunner as a field on service struct is forbidden.",
					"Remove field and call 's.GetTransactionRunner().Run(ctx, func(txCtx context.Context) error { ... })' via embedded ServiceBase.",
				)
			}

			// Check if field is a repository
			if isRepositoryType(typeStr) {
				repoFields++
				for _, name := range field.Names {
					if name.Name != "repository" {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Service Struct",
							"In service structs, the service's primary repository field MUST be named 'repository'.",
							fmt.Sprintf("Primary repository field is named '%s' instead of 'repository'.", name.Name),
							fmt.Sprintf("Rename struct field '%s' to 'repository %s'.", name.Name, typeStr),
						)
					}
				}
			}

			// Check sibling services: must be lowercase acronym
			if isSiblingServiceType(typeStr) {
				expectedAcronym := computeAcronym(typeStr)
				for _, name := range field.Names {
					if name.Name != expectedAcronym {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Sibling Services",
							"Injected sibling services MUST be named by strict lowercase acronyms of their interface type.",
							fmt.Sprintf("Sibling service field '%s' of type '%s' does not use expected acronym '%s'.", name.Name, typeStr, expectedAcronym),
							fmt.Sprintf("Rename struct field '%s' to '%s %s'.", name.Name, expectedAcronym, typeStr),
						)
					}
				}
			}
		}

		if repoFields > 1 {
			v.addViolation(
				pos,
				"Service Struct",
				"A service must ONLY hold its own repository. Sibling domains must be accessed strictly through their service interface.",
				"Service struct holds multiple repository interfaces.",
				"Remove foreign repositories. Inject sibling service interfaces instead.",
			)
		}
	} else if isInternal && !isMock && !isTestFile {
		// Check other structs in internal/ (e.g. Deps, Runner, Supervisor, etc.)
		for _, field := range st.Fields.List {
			typeStr := formatTypeExpr(field.Type)

			// Service fields in any internal struct must be unexported and use lowercase acronym
			if isSiblingServiceType(typeStr) {
				expectedAcronym := computeAcronym(typeStr)
				for _, name := range field.Names {
					if unicode.IsUpper(rune(name.Name[0])) || (!isEndpointDir && name.Name != expectedAcronym) {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Sibling Services",
							"Service interface fields on structs must be unexported lowercase acronyms (e.g. 'cs ports.CreditService').",
							fmt.Sprintf("Service field '%s' of type '%s' on struct '%s' must be an unexported lowercase acronym '%s'.", name.Name, typeStr, ts.Name.Name, expectedAcronym),
							fmt.Sprintf("Rename struct field '%s' to '%s %s'.", name.Name, expectedAcronym, typeStr),
						)
					}
				}
			}

			// Repository fields in any non-Service internal struct must not be exported
			if isRepositoryType(typeStr) {
				for _, name := range field.Names {
					if unicode.IsUpper(rune(name.Name[0])) {
						unexportedName := deriveUnexportedName(name.Name)
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Dependencies",
							"Repository fields on structs must be unexported; direct external access to repository struct fields is forbidden.",
							fmt.Sprintf("Repository field '%s' on struct '%s' is exported.", name.Name, ts.Name.Name),
							fmt.Sprintf("Make field unexported (e.g. '%s') and expose via getter method 'Get%s() %s'.", unexportedName, name.Name, typeStr),
						)
					}
				}
			}
		}
	}

	// Check Empty Response Structs in endpoint handlers
	if isEndpointDir && strings.HasSuffix(ts.Name.Name, "Response") {
		if len(st.Fields.List) == 0 {
			v.addViolation(
				pos,
				"HTTP Handlers",
				"Handlers returning no data return hextransport.NewSuccessResponse().ToJSON(c) without arguments; never define empty response structs.",
				fmt.Sprintf("Empty response struct '%s' with 0 fields is forbidden.", ts.Name.Name),
				fmt.Sprintf("Delete struct '%s' and return 'hextransport.NewSuccessResponse().ToJSON(c)' without arguments in handler.", ts.Name.Name),
			)
		}
	}

	// Check forbidden oneof= in request struct tags
	if isEndpointDir && strings.HasSuffix(ts.Name.Name, "Request") {
		for _, field := range st.Fields.List {
			if field.Tag != nil {
				tagStr := field.Tag.Value
				if strings.Contains(tagStr, "oneof=") || strings.Contains(tagStr, "oneof =") {
					fieldName := ""
					if len(field.Names) > 0 {
						fieldName = field.Names[0].Name
					}
					v.addViolation(
						v.fset.Position(field.Pos()),
						"Validation",
						"Hardcoding enum values with 'oneof=...' in validator tags is forbidden. Use a typed domain enum implementing hexports.Validatable (IsValid() bool); the framework validator autodetects it automatically.",
						fmt.Sprintf("Field '%s' in struct '%s' uses forbidden hardcoded validation tag 'oneof='.", fieldName, ts.Name.Name),
						"Remove 'oneof=...' from tag and use a typed domain enum implementing IsValid() bool. The framework validator will autodetect and validate it.",
					)
				}
			}
		}
	}
}

func (v *Verifier) checkFuncDecl(filePath string, fn *ast.FuncDecl, isServiceDir, isEndpointDir, isPortsDomain bool) {
	pos := v.fset.Position(fn.Pos())

	// Check if this method implements IsValid() bool for an enum type
	if fn.Name.Name == "IsValid" && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		recvType = strings.TrimPrefix(recvType, "*")
		if fn.Type.Params == nil || len(fn.Type.Params.List) == 0 {
			if fn.Type.Results != nil && len(fn.Type.Results.List) == 1 {
				if formatTypeExpr(fn.Type.Results.List[0].Type) == "bool" {
					v.portsEnumMethods[recvType] = true
					if fn.Body != nil {
						if v.portsEnumHandledValues[recvType] == nil {
							v.portsEnumHandledValues[recvType] = make(map[string]bool)
						}
						ast.Inspect(fn.Body, func(n ast.Node) bool {
							if id, ok := n.(*ast.Ident); ok {
								v.portsEnumHandledValues[recvType][id.Name] = true
							}
							return true
						})
					}
				}
			}
		}
	}

	// Check Service constructor
	if isServiceDir && fn.Name.Name == "NewService" && fn.Type.Params != nil {
		repoCount := 0
		for _, param := range fn.Type.Params.List {
			typeStr := formatTypeExpr(param.Type)
			if strings.Contains(typeStr, "TransactionRunner") {
				v.addViolation(
					pos,
					"Tx Runner",
					"Never pass TransactionRunner directly through service constructors; access it via ServiceContext/ServiceBase.",
					"Passing TransactionRunner to NewService constructor is forbidden.",
					"Remove TransactionRunner parameter from NewService(...); call s.GetTransactionRunner().Run(...) via base service.",
				)
			}
			if isRepositoryType(typeStr) {
				repoCount++
				for _, name := range param.Names {
					if name.Name != "repository" {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Service Struct",
							"In NewService constructor, the primary repository parameter MUST be named 'repository'.",
							fmt.Sprintf("Primary repository parameter is named '%s' instead of 'repository'.", name.Name),
							fmt.Sprintf("Rename parameter '%s' to 'repository %s'.", name.Name, typeStr),
						)
					}
				}
			}
			if isSiblingServiceType(typeStr) {
				expectedAcronym := computeAcronym(typeStr)
				for _, name := range param.Names {
					if name.Name != expectedAcronym {
						v.addViolation(
							v.fset.Position(name.Pos()),
							"Sibling Services",
							"In NewService constructor, sibling service parameters MUST be named by strict lowercase acronyms of their interface type.",
							fmt.Sprintf("Sibling service parameter '%s' of type '%s' does not use expected acronym '%s'.", name.Name, typeStr, expectedAcronym),
							fmt.Sprintf("Rename parameter '%s' to '%s %s'.", name.Name, expectedAcronym, typeStr),
						)
					}
				}
			}
		}
		if repoCount > 1 {
			v.addViolation(
				pos,
				"Service Struct",
				"A service must ONLY hold its own repository. Never inject another service's repository directly.",
				"Injecting foreign repositories into NewService constructor is forbidden.",
				"Inject the sibling service interface instead of another domain's repository.",
			)
		}
	}

	// Check setter injection on Service (With...)
	if isServiceDir && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		if strings.Contains(recvType, "Service") && strings.HasPrefix(fn.Name.Name, "With") {
			v.addViolation(
				pos,
				"Service Struct",
				"Cyclic dependencies and setter injection workarounds (With...) are strictly prohibited.",
				fmt.Sprintf("Setter injection method '%s' is forbidden on service struct.", fn.Name.Name),
				"Inject all dependencies via constructor NewService(...). Extract shared logic into an orchestrator service if needed.",
			)
		}
	}

	// Check exported handler methods on Handler structs
	if isEndpointDir && fn.Recv != nil && len(fn.Recv.List) > 0 {
		recvType := formatTypeExpr(fn.Recv.List[0].Type)
		if strings.HasSuffix(recvType, "Handler") && fn.Type.Params != nil {
			// Check if method takes fiber.Ctx
			for _, param := range fn.Type.Params.List {
				paramType := formatTypeExpr(param.Type)
				if strings.Contains(paramType, "Ctx") {
					if !ast.IsExported(fn.Name.Name) && fn.Name.Name != "Register" {
						exportedName := deriveExportedName(fn.Name.Name)
						v.addViolation(
							pos,
							"HTTP Handlers",
							"All handler methods MUST be exported with capitalized names: (h <Service>Handler) <MethodName>(c fiber.Ctx) error.",
							fmt.Sprintf("Handler method '%s' is unexported (starts with lowercase).", fn.Name.Name),
							fmt.Sprintf("Capitalize the method name: change '%s' to '%s(c fiber.Ctx) error'.", fn.Name.Name, exportedName),
						)
					}
					break
				}
			}
		}
	}

	// Check CollectionName singular snake_case in domain.go
	if isPortsDomain && fn.Name.Name == "CollectionName" && fn.Body != nil {
		for _, stmt := range fn.Body.List {
			retStmt, ok := stmt.(*ast.ReturnStmt)
			if !ok || len(retStmt.Results) == 0 {
				continue
			}
			lit, isLit := retStmt.Results[0].(*ast.BasicLit)
			if !isLit || lit.Kind != token.STRING {
				continue
			}
			name := strings.Trim(lit.Value, `"`)
			if isPluralCollection(name) {
				v.addViolation(
					pos,
					"Collections",
					"Mongo collection names are singular snake_case (e.g. 'user', 'subscription_tier').",
					fmt.Sprintf("Collection name '%s' appears to be plural.", name),
					fmt.Sprintf("Change collection name to singular snake_case (e.g. '%s').", strings.TrimSuffix(name, "s")),
				)
			}
		}
	}
}

func (v *Verifier) checkCallExpr(filePath string, call *ast.CallExpr, isServiceDir, isEndpointDir, isDatabaseDir, isTestFile bool, importedPackages map[string]bool) {
	pos := v.fset.Position(call.Pos())

	// Check time.Now() in services or endpoints (not tests)
	if (isServiceDir || isEndpointDir) && !isTestFile {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
			if ident, ok := sel.X.(*ast.Ident); ok && ident.Name == "time" && sel.Sel.Name == "Now" {
				v.addViolation(
					pos,
					"Time Handling",
					"Capture request time once via 'at := hextransport.RequestTime(c)' and pass 'at' through; never invoke time.Now() in services/handlers.",
					"Calling time.Now() in services or HTTP handlers is forbidden.",
					"Pass 'at time.Time' as a parameter. In HTTP handlers, capture once via 'at := hextransport.RequestTime(c)'.",
				)
			}
		}
	}

	// Check c.Query(...) in endpoint handlers
	if isEndpointDir {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Query" {
			v.addViolation(
				pos,
				"HTTP Queries",
				"Bind request DTOs via hextransport.Bind(c, &req) or hextransport.BindQuery(c, &req); never manually parse query parameters with c.Query().",
				"Direct query parameter access with c.Query(...) is forbidden.",
				"Define a request query struct (with `query:\"...\"` tags) and bind via 'hextransport.BindQuery(c, &req)'.",
			)
		}
	}

	// Check hardcoded db.Collection("...") in database repositories
	if isDatabaseDir {
		if sel, ok := call.Fun.(*ast.SelectorExpr); ok && sel.Sel.Name == "Collection" && len(call.Args) > 0 {
			if lit, ok := call.Args[0].(*ast.BasicLit); ok && lit.Kind == token.STRING {
				v.addViolation(
					pos,
					"Collections",
					"Always obtain collection names via ports.<Entity>Model{}.CollectionName(); never hardcode collection name strings.",
					fmt.Sprintf("Hardcoded collection name string %s is forbidden in db.Collection(...).", lit.Value),
					fmt.Sprintf("Replace %s with ports.<Entity>Model{}.CollectionName().", lit.Value),
				)
			}
		}
	}

	// Check abbreviated getter method calls (e.g. .GetConnectionRepo())
	if sel, ok := call.Fun.(*ast.SelectorExpr); ok {
		if ident, ok := sel.X.(*ast.Ident); ok && importedPackages[ident.Name] {
			return
		}
		name := sel.Sel.Name
		if strings.HasPrefix(name, "Get") && strings.HasSuffix(name, "Repo") {
			correctGetter := deriveGetterName(name)
			v.addViolation(
				pos,
				"Dependencies",
				"Interface-based dependencies use full-word getter methods; never use shortened abbreviations (e.g. GetConnectionRepository(), not GetConnectionRepo()).",
				fmt.Sprintf("Abbreviated getter method call '%s()' is forbidden.", name),
				fmt.Sprintf("Call full method name '%s' instead.", correctGetter),
			)
		} else if !isTestFile && strings.HasSuffix(name, "Repository") && !strings.HasPrefix(name, "Get") && !strings.HasPrefix(name, "New") {
			v.addViolation(
				pos,
				"Dependencies",
				"Interface-based dependencies use full-word getter methods starting with 'Get' (e.g. GetConnectionRepository()).",
				fmt.Sprintf("Getter method call '%s()' must start with 'Get'.", name),
				fmt.Sprintf("Call 'Get%s()' instead.", name),
			)
		}
	}
}

func (v *Verifier) checkBinaryExpr(filePath string, bin *ast.BinaryExpr, isServiceDir bool) {
	pos := v.fset.Position(bin.Pos())

	// Check sentinel equality: err == ports.ErrNotFound or err != ports.ErrNotFound
	if bin.Op == token.EQL || bin.Op == token.NEQ {
		leftStr := exprToString(bin.X)
		rightStr := exprToString(bin.Y)

		if isErrSentinel(leftStr) || isErrSentinel(rightStr) {
			opStr := "=="
			if bin.Op == token.NEQ {
				opStr = "!="
			}
			sentinel := getSentinelExpr(leftStr, rightStr)
			v.addViolation(
				pos,
				"Sentinels",
				"Compare sentinels only with errors.Is(err, ports.ErrX); never ==, !=, or switch err.",
				fmt.Sprintf("Direct sentinel comparison '%s %s %s' is forbidden.", leftStr, opStr, rightStr),
				fmt.Sprintf("Replace direct comparison with 'errors.Is(err, %s)'.", sentinel),
			)
		}

		// Check nil checks on injected sibling services: if s.us == nil
		if isServiceDir {
			if isNilExpr(bin.X) && isServiceSelector(bin.Y) {
				serviceExpr := exprToString(bin.Y)
				v.addViolation(
					pos,
					"Sibling Services",
					"Injected service interfaces are NEVER nil. Never write nil checks (if s.us != nil).",
					fmt.Sprintf("Nil check on injected sibling service '%s' is forbidden.", serviceExpr),
					fmt.Sprintf("Remove nil check guard on '%s'. Dependencies are guaranteed non-nil via constructor NewService(...).", serviceExpr),
				)
			} else if isNilExpr(bin.Y) && isServiceSelector(bin.X) {
				serviceExpr := exprToString(bin.X)
				v.addViolation(
					pos,
					"Sibling Services",
					"Injected service interfaces are NEVER nil. Never write nil checks (if s.us != nil).",
					fmt.Sprintf("Nil check on injected sibling service '%s' is forbidden.", serviceExpr),
					fmt.Sprintf("Remove nil check guard on '%s'. Dependencies are guaranteed non-nil via constructor NewService(...).", serviceExpr),
				)
			}
		}
	}
}

func (v *Verifier) checkSwitchStmt(filePath string, sw *ast.SwitchStmt) {
	if sw.Tag == nil {
		return
	}
	tagStr := exprToString(sw.Tag)
	if tagStr == "err" || strings.HasSuffix(tagStr, "Err") || strings.HasSuffix(tagStr, "Error") {
		for _, stmt := range sw.Body.List {
			if cc, ok := stmt.(*ast.CaseClause); ok {
				for _, expr := range cc.List {
					exprStr := exprToString(expr)
					if isErrSentinel(exprStr) {
						v.addViolation(
							v.fset.Position(expr.Pos()),
							"Sentinels",
							"Compare sentinels only with errors.Is(err, ports.ErrX); never switch err.",
							fmt.Sprintf("Switch case on error sentinel '%s' is forbidden.", exprStr),
							fmt.Sprintf("Replace switch with 'if errors.Is(err, %s)' checks.", exprStr),
						)
					}
				}
			}
		}
	}
}

func (v *Verifier) checkSelectorExpr(filePath string, sel *ast.SelectorExpr, importedPackages map[string]bool, isCallFun, isTestFile bool) {
	// Selector checks apply to production code, not unit test fixtures
	if isTestFile {
		return
	}

	// Ignore package selectors like repo.SomeFunc, ports.UserRepository, time.Now
	if ident, ok := sel.X.(*ast.Ident); ok && importedPackages[ident.Name] {
		return
	}

	name := sel.Sel.Name

	// 1. Check direct struct field access to *Repo: s.deps.ConnectionRepo or deps.ConnectionRepo
	if strings.HasSuffix(name, "Repo") && name != "repo" && !strings.HasPrefix(name, "Get") {
		correctGetter := deriveGetterName(name)
		v.addViolation(
			v.fset.Position(sel.Pos()),
			"Dependencies",
			"Interface-based dependencies use full-word getter methods; direct struct field accesses or abbreviations like '*Repo' are forbidden.",
			fmt.Sprintf("Direct field access or abbreviated name '%s' is forbidden.", name),
			fmt.Sprintf("Call getter method '%s' instead of accessing field '%s'.", correctGetter, name),
		)
		return
	}

	// 2. Check direct struct field access to *Repository: s.deps.ConnectionRepository or deps.ConnectionRepository
	if strings.HasSuffix(name, "Repository") && name != "repository" && !strings.HasPrefix(name, "Get") {
		v.addViolation(
			v.fset.Position(sel.Pos()),
			"Dependencies",
			"Interface-based dependencies use full-word getter methods; direct struct field access to repository fields is forbidden.",
			fmt.Sprintf("Direct struct field access to repository '%s' is forbidden.", name),
			fmt.Sprintf("Call getter method 'Get%s()' instead of accessing field '%s'.", name, name),
		)
		return
	}

	// 3. Check direct struct field access to *Service (not called as a function): s.deps.CreditService or deps.AccountService
	if !isCallFun && strings.HasSuffix(name, "Service") && !strings.HasPrefix(name, "Get") {
		v.addViolation(
			v.fset.Position(sel.Pos()),
			"Sibling Services",
			"Injected sibling services must be stored in unexported acronym fields (e.g. 's.cs') on service structs or accessed via getter methods (e.g. 'GetCreditService()'); direct struct field access to service full names is forbidden.",
			fmt.Sprintf("Direct struct field access to service '%s' is forbidden.", name),
			fmt.Sprintf("Call getter method 'Get%s()' or inject via constructor NewService(...).", name),
		)
		return
	}
}

func (v *Verifier) checkValueSpec(filePath string, vs *ast.ValueSpec) {
	// Check for CollectionName = "..." constant or variable
	for _, name := range vs.Names {
		if name.Name == "CollectionName" {
			v.addViolation(
				v.fset.Position(name.Pos()),
				"Collections",
				"Collection names must be obtained from model's CollectionName() method, not string constants.",
				"Defining 'CollectionName' as a string constant or variable is forbidden.",
				"Implement 'func (m <Entity>Model) CollectionName() string' on the model struct.",
			)
		}
	}
}

// Helpers

func deriveGetterName(name string) string {
	if strings.HasPrefix(name, "Get") && strings.HasSuffix(name, "Repo") {
		return name[:len(name)-4] + "Repository()"
	}
	if strings.HasSuffix(name, "Repo") {
		base := strings.TrimSuffix(name, "Repo")
		return "Get" + base + "Repository()"
	}
	if strings.HasSuffix(name, "Repository") {
		return "Get" + name + "()"
	}
	return "Get" + name + "()"
}

func deriveUnexportedName(name string) string {
	if name == "" {
		return ""
	}
	r := []rune(name)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func deriveExportedName(name string) string {
	if name == "" {
		return ""
	}
	r := []rune(name)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func formatTypeExpr(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return formatTypeExpr(t.X) + "." + t.Sel.Name
	case *ast.StarExpr:
		return "*" + formatTypeExpr(t.X)
	default:
		return ""
	}
}

func isRepositoryType(typeStr string) bool {
	return strings.HasSuffix(typeStr, "Repository") && !strings.Contains(typeStr, "QueueRepository")
}

func isSiblingServiceType(typeStr string) bool {
	return strings.HasSuffix(typeStr, "Service") &&
		!strings.Contains(typeStr, "ServiceBase") &&
		!strings.Contains(typeStr, "QueueService")
}

func computeAcronym(typeStr string) string {
	parts := strings.Split(typeStr, ".")
	leaf := parts[len(parts)-1]
	leaf = strings.TrimPrefix(leaf, "*")

	var letters []rune
	for _, r := range leaf {
		if unicode.IsUpper(r) {
			letters = append(letters, unicode.ToLower(r))
		}
	}
	return string(letters)
}

func isErrSentinel(str string) bool {
	if strings.HasPrefix(str, "ports.Err") {
		return true
	}
	if strings.HasPrefix(str, "Err") && str != "Error" {
		return true
	}
	if strings.Contains(str, ".Err") {
		return true
	}
	return false
}

func getSentinelExpr(left, right string) string {
	if isErrSentinel(left) {
		return left
	}
	return right
}

func isNilExpr(expr ast.Expr) bool {
	if ident, ok := expr.(*ast.Ident); ok && ident.Name == "nil" {
		return true
	}
	return false
}

func isServiceSelector(expr ast.Expr) bool {
	sel, ok := expr.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	fieldName := sel.Sel.Name
	if fieldName == "repository" || fieldName == "ServiceBase" || fieldName == "ctx" {
		return false
	}
	return isServiceAcronym(fieldName)
}

func isServiceAcronym(str string) bool {
	// e.g. us, cs, bcs, abcs, userService
	clean := str
	if idx := strings.LastIndex(str, "."); idx != -1 {
		clean = str[idx+1:]
	}
	if clean == "err" || clean == "ctx" || clean == "nil" || clean == "ok" {
		return false
	}
	if strings.HasSuffix(clean, "Service") || strings.HasSuffix(clean, "Svc") {
		return true
	}
	// 2 to 4 lowercase letters, e.g. "us", "cs", "bcs", "abcs"
	if len(clean) >= 2 && len(clean) <= 4 {
		for _, r := range clean {
			if !unicode.IsLower(r) {
				return false
			}
		}
		return true
	}
	return false
}

func isPluralCollection(name string) bool {
	if !strings.HasSuffix(name, "s") {
		return false
	}
	singularExceptions := map[string]bool{
		"status":   true,
		"address":  true,
		"access":   true,
		"process":  true,
		"bus":      true,
		"class":    true,
		"lens":     true,
		"basis":    true,
		"analysis": true,
		"canvas":   true,
		"compass":  true,
		"crisis":   true,
		"alias":    true,
		"bonus":    true,
		"news":     true,
		"series":   true,
		"species":  true,
	}
	return !singularExceptions[name]
}

func exprToString(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return exprToString(e.X) + "." + e.Sel.Name
	case *ast.StarExpr:
		return "*" + exprToString(e.X)
	case *ast.BasicLit:
		return e.Value
	default:
		return ""
	}
}

func (v *Verifier) checkFinalInvariants() {
	if v.invariantsChecked {
		return
	}
	v.invariantsChecked = true

	for typeName, pos := range v.portsEnumTypes {
		if !v.portsEnumMethods[typeName] {
			v.addViolation(
				pos,
				"Enums",
				"All domain enums defined in internal/ports MUST implement 'IsValid() bool' (implementing hexports.Validatable).",
				fmt.Sprintf("Domain enum type '%s' does not implement 'IsValid() bool'.", typeName),
				fmt.Sprintf("Implement 'func (e %s) IsValid() bool' with a switch statement covering all declared %s constants.", typeName, typeName),
			)
			continue
		}

		handled := v.portsEnumHandledValues[typeName]
		for _, constant := range v.portsEnumConstants[typeName] {
			if !handled[constant.name] {
				v.addViolation(
					constant.pos,
					"Enums",
					fmt.Sprintf("The 'IsValid() bool' method on domain enum '%s' must handle all declared constants.", typeName),
					fmt.Sprintf("Enum constant '%s' of type '%s' is not checked in 'IsValid()'.", constant.name, typeName),
					fmt.Sprintf("Add '%s' to the switch statement in 'func (e %s) IsValid() bool'.", constant.name, typeName),
				)
			}
		}
	}
}

func isBuiltinGoType(t string) bool {
	switch t {
	case "string", "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128",
		"bool", "byte", "rune", "error", "any",
		"time.Duration", "time.Time":
		return true
	default:
		return false
	}
}
