// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/king-glitch/hexag/framework/ports"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/v2/bson"
)

// NewMockTransactionRunner creates a new instance of MockTransactionRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransactionRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransactionRunner {
	mock := &MockTransactionRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransactionRunner is an autogenerated mock type for the TransactionRunner type
type MockTransactionRunner struct {
	mock.Mock
}

type MockTransactionRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransactionRunner) EXPECT() *MockTransactionRunner_Expecter {
	return &MockTransactionRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockTransactionRunner
func (_mock *MockTransactionRunner) Run(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTransactionRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockTransactionRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTransactionRunner_Expecter) Run(ctx any, fn any) *MockTransactionRunner_Run_Call {
	return &MockTransactionRunner_Run_Call{Call: _e.mock.On("Run", ctx, fn)}
}

func (_c *MockTransactionRunner_Run_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTransactionRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTransactionRunner_Run_Call) Return(err error) *MockTransactionRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTransactionRunner_Run_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTransactionRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServiceContext creates a new instance of MockServiceContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServiceContext(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServiceContext {
	mock := &MockServiceContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockServiceContext is an autogenerated mock type for the ServiceContext type
type MockServiceContext struct {
	mock.Mock
}

type MockServiceContext_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServiceContext) EXPECT() *MockServiceContext_Expecter {
	return &MockServiceContext_Expecter{mock: &_m.Mock}
}

// Logger provides a mock function for the type MockServiceContext
func (_mock *MockServiceContext) Logger() *zerolog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *zerolog.Logger
	if returnFunc, ok := ret.Get(0).(func() *zerolog.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*zerolog.Logger)
		}
	}
	return r0
}

// MockServiceContext_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockServiceContext_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockServiceContext_Expecter) Logger() *MockServiceContext_Logger_Call {
	return &MockServiceContext_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockServiceContext_Logger_Call) Run(run func()) *MockServiceContext_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServiceContext_Logger_Call) Return(logger *zerolog.Logger) *MockServiceContext_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockServiceContext_Logger_Call) RunAndReturn(run func() *zerolog.Logger) *MockServiceContext_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockModel creates a new instance of MockModel. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModel(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModel {
	mock := &MockModel{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModel is an autogenerated mock type for the Model type
type MockModel struct {
	mock.Mock
}

type MockModel_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModel) EXPECT() *MockModel_Expecter {
	return &MockModel_Expecter{mock: &_m.Mock}
}

// CollectionName provides a mock function for the type MockModel
func (_mock *MockModel) CollectionName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectionName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockModel_CollectionName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectionName'
type MockModel_CollectionName_Call struct {
	*mock.Call
}

// CollectionName is a helper method to define mock.On call
func (_e *MockModel_Expecter) CollectionName() *MockModel_CollectionName_Call {
	return &MockModel_CollectionName_Call{Call: _e.mock.On("CollectionName")}
}

func (_c *MockModel_CollectionName_Call) Run(run func()) *MockModel_CollectionName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModel_CollectionName_Call) Return(s string) *MockModel_CollectionName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockModel_CollectionName_Call) RunAndReturn(run func() string) *MockModel_CollectionName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBaseSetter creates a new instance of MockBaseSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBaseSetter[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBaseSetter[T] {
	mock := &MockBaseSetter[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBaseSetter is an autogenerated mock type for the BaseSetter type
type MockBaseSetter[T any] struct {
	mock.Mock
}

type MockBaseSetter_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockBaseSetter[T]) EXPECT() *MockBaseSetter_Expecter[T] {
	return &MockBaseSetter_Expecter[T]{mock: &_m.Mock}
}

// WithBase provides a mock function for the type MockBaseSetter
func (_mock *MockBaseSetter[T]) WithBase(modelBase ports.ModelBase) T {
	ret := _mock.Called(modelBase)

	if len(ret) == 0 {
		panic("no return value specified for WithBase")
	}

	var r0 T
	if returnFunc, ok := ret.Get(0).(func(ports.ModelBase) T); ok {
		r0 = returnFunc(modelBase)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}
	return r0
}

// MockBaseSetter_WithBase_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithBase'
type MockBaseSetter_WithBase_Call[T any] struct {
	*mock.Call
}

// WithBase is a helper method to define mock.On call
//   - modelBase ports.ModelBase
func (_e *MockBaseSetter_Expecter[T]) WithBase(modelBase any) *MockBaseSetter_WithBase_Call[T] {
	return &MockBaseSetter_WithBase_Call[T]{Call: _e.mock.On("WithBase", modelBase)}
}

func (_c *MockBaseSetter_WithBase_Call[T]) Run(run func(modelBase ports.ModelBase)) *MockBaseSetter_WithBase_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.ModelBase
		if args[0] != nil {
			arg0 = args[0].(ports.ModelBase)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBaseSetter_WithBase_Call[T]) Return(v T) *MockBaseSetter_WithBase_Call[T] {
	_c.Call.Return(v)
	return _c
}

func (_c *MockBaseSetter_WithBase_Call[T]) RunAndReturn(run func(modelBase ports.ModelBase) T) *MockBaseSetter_WithBase_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueItem creates a new instance of MockQueueItem. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueItem(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueItem {
	mock := &MockQueueItem{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueItem is an autogenerated mock type for the QueueItem type
type MockQueueItem struct {
	mock.Mock
}

type MockQueueItem_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueItem) EXPECT() *MockQueueItem_Expecter {
	return &MockQueueItem_Expecter{mock: &_m.Mock}
}

// GetActionType provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) GetActionType() ports.ActionType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetActionType")
	}

	var r0 ports.ActionType
	if returnFunc, ok := ret.Get(0).(func() ports.ActionType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.ActionType)
	}
	return r0
}

// MockQueueItem_GetActionType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActionType'
type MockQueueItem_GetActionType_Call struct {
	*mock.Call
}

// GetActionType is a helper method to define mock.On call
func (_e *MockQueueItem_Expecter) GetActionType() *MockQueueItem_GetActionType_Call {
	return &MockQueueItem_GetActionType_Call{Call: _e.mock.On("GetActionType")}
}

func (_c *MockQueueItem_GetActionType_Call) Run(run func()) *MockQueueItem_GetActionType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueItem_GetActionType_Call) Return(actionType ports.ActionType) *MockQueueItem_GetActionType_Call {
	_c.Call.Return(actionType)
	return _c
}

func (_c *MockQueueItem_GetActionType_Call) RunAndReturn(run func() ports.ActionType) *MockQueueItem_GetActionType_Call {
	_c.Call.Return(run)
	return _c
}

// GetData provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) GetData() any {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetData")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockQueueItem_GetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetData'
type MockQueueItem_GetData_Call struct {
	*mock.Call
}

// GetData is a helper method to define mock.On call
func (_e *MockQueueItem_Expecter) GetData() *MockQueueItem_GetData_Call {
	return &MockQueueItem_GetData_Call{Call: _e.mock.On("GetData")}
}

func (_c *MockQueueItem_GetData_Call) Run(run func()) *MockQueueItem_GetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueItem_GetData_Call) Return(v any) *MockQueueItem_GetData_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockQueueItem_GetData_Call) RunAndReturn(run func() any) *MockQueueItem_GetData_Call {
	_c.Call.Return(run)
	return _c
}

// GetId provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) GetId() bson.ObjectID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetId")
	}

	var r0 bson.ObjectID
	if returnFunc, ok := ret.Get(0).(func() bson.ObjectID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.ObjectID)
		}
	}
	return r0
}

// MockQueueItem_GetId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetId'
type MockQueueItem_GetId_Call struct {
	*mock.Call
}

// GetId is a helper method to define mock.On call
func (_e *MockQueueItem_Expecter) GetId() *MockQueueItem_GetId_Call {
	return &MockQueueItem_GetId_Call{Call: _e.mock.On("GetId")}
}

func (_c *MockQueueItem_GetId_Call) Run(run func()) *MockQueueItem_GetId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueItem_GetId_Call) Return(objectID bson.ObjectID) *MockQueueItem_GetId_Call {
	_c.Call.Return(objectID)
	return _c
}

func (_c *MockQueueItem_GetId_Call) RunAndReturn(run func() bson.ObjectID) *MockQueueItem_GetId_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessage provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) GetMessage() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMessage")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockQueueItem_GetMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessage'
type MockQueueItem_GetMessage_Call struct {
	*mock.Call
}

// GetMessage is a helper method to define mock.On call
func (_e *MockQueueItem_Expecter) GetMessage() *MockQueueItem_GetMessage_Call {
	return &MockQueueItem_GetMessage_Call{Call: _e.mock.On("GetMessage")}
}

func (_c *MockQueueItem_GetMessage_Call) Run(run func()) *MockQueueItem_GetMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueItem_GetMessage_Call) Return(s string) *MockQueueItem_GetMessage_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockQueueItem_GetMessage_Call) RunAndReturn(run func() string) *MockQueueItem_GetMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetPriority provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) GetPriority() ports.Priority {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPriority")
	}

	var r0 ports.Priority
	if returnFunc, ok := ret.Get(0).(func() ports.Priority); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.Priority)
	}
	return r0
}

// MockQueueItem_GetPriority_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPriority'
type MockQueueItem_GetPriority_Call struct {
	*mock.Call
}

// GetPriority is a helper method to define mock.On call
func (_e *MockQueueItem_Expecter) GetPriority() *MockQueueItem_GetPriority_Call {
	return &MockQueueItem_GetPriority_Call{Call: _e.mock.On("GetPriority")}
}

func (_c *MockQueueItem_GetPriority_Call) Run(run func()) *MockQueueItem_GetPriority_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueItem_GetPriority_Call) Return(priority ports.Priority) *MockQueueItem_GetPriority_Call {
	_c.Call.Return(priority)
	return _c
}

func (_c *MockQueueItem_GetPriority_Call) RunAndReturn(run func() ports.Priority) *MockQueueItem_GetPriority_Call {
	_c.Call.Return(run)
	return _c
}

// GetScheduledAt provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) GetScheduledAt() *time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetScheduledAt")
	}

	var r0 *time.Time
	if returnFunc, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}
	return r0
}

// MockQueueItem_GetScheduledAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetScheduledAt'
type MockQueueItem_GetScheduledAt_Call struct {
	*mock.Call
}

// GetScheduledAt is a helper method to define mock.On call
func (_e *MockQueueItem_Expecter) GetScheduledAt() *MockQueueItem_GetScheduledAt_Call {
	return &MockQueueItem_GetScheduledAt_Call{Call: _e.mock.On("GetScheduledAt")}
}

func (_c *MockQueueItem_GetScheduledAt_Call) Run(run func()) *MockQueueItem_GetScheduledAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueItem_GetScheduledAt_Call) Return(time1 *time.Time) *MockQueueItem_GetScheduledAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockQueueItem_GetScheduledAt_Call) RunAndReturn(run func() *time.Time) *MockQueueItem_GetScheduledAt_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) GetStatus() ports.QueueItemStatus {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 ports.QueueItemStatus
	if returnFunc, ok := ret.Get(0).(func() ports.QueueItemStatus); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(ports.QueueItemStatus)
	}
	return r0
}

// MockQueueItem_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockQueueItem_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
func (_e *MockQueueItem_Expecter) GetStatus() *MockQueueItem_GetStatus_Call {
	return &MockQueueItem_GetStatus_Call{Call: _e.mock.On("GetStatus")}
}

func (_c *MockQueueItem_GetStatus_Call) Run(run func()) *MockQueueItem_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueItem_GetStatus_Call) Return(queueItemStatus ports.QueueItemStatus) *MockQueueItem_GetStatus_Call {
	_c.Call.Return(queueItemStatus)
	return _c
}

func (_c *MockQueueItem_GetStatus_Call) RunAndReturn(run func() ports.QueueItemStatus) *MockQueueItem_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// SetData provides a mock function for the type MockQueueItem
func (_mock *MockQueueItem) SetData(data any) {
	_mock.Called(data)
	return
}

// MockQueueItem_SetData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetData'
type MockQueueItem_SetData_Call struct {
	*mock.Call
}

// SetData is a helper method to define mock.On call
//   - data any
func (_e *MockQueueItem_Expecter) SetData(data any) *MockQueueItem_SetData_Call {
	return &MockQueueItem_SetData_Call{Call: _e.mock.On("SetData", data)}
}

func (_c *MockQueueItem_SetData_Call) Run(run func(data any)) *MockQueueItem_SetData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 any
		if args[0] != nil {
			arg0 = args[0].(any)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueueItem_SetData_Call) Return() *MockQueueItem_SetData_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockQueueItem_SetData_Call) RunAndReturn(run func(data any)) *MockQueueItem_SetData_Call {
	_c.Run(run)
	return _c
}

// NewMockTransformer creates a new instance of MockTransformer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTransformer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTransformer {
	mock := &MockTransformer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTransformer is an autogenerated mock type for the Transformer type
type MockTransformer struct {
	mock.Mock
}

type MockTransformer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTransformer) EXPECT() *MockTransformer_Expecter {
	return &MockTransformer_Expecter{mock: &_m.Mock}
}

// Transform provides a mock function for the type MockTransformer
func (_mock *MockTransformer) Transform(queueModel ports.QueueModel) (ports.QueueItem, error) {
	ret := _mock.Called(queueModel)

	if len(ret) == 0 {
		panic("no return value specified for Transform")
	}

	var r0 ports.QueueItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(ports.QueueModel) (ports.QueueItem, error)); ok {
		return returnFunc(queueModel)
	}
	if returnFunc, ok := ret.Get(0).(func(ports.QueueModel) ports.QueueItem); ok {
		r0 = returnFunc(queueModel)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.QueueItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(ports.QueueModel) error); ok {
		r1 = returnFunc(queueModel)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTransformer_Transform_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transform'
type MockTransformer_Transform_Call struct {
	*mock.Call
}

// Transform is a helper method to define mock.On call
//   - queueModel ports.QueueModel
func (_e *MockTransformer_Expecter) Transform(queueModel any) *MockTransformer_Transform_Call {
	return &MockTransformer_Transform_Call{Call: _e.mock.On("Transform", queueModel)}
}

func (_c *MockTransformer_Transform_Call) Run(run func(queueModel ports.QueueModel)) *MockTransformer_Transform_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ports.QueueModel
		if args[0] != nil {
			arg0 = args[0].(ports.QueueModel)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTransformer_Transform_Call) Return(queueItem ports.QueueItem, err error) *MockTransformer_Transform_Call {
	_c.Call.Return(queueItem, err)
	return _c
}

func (_c *MockTransformer_Transform_Call) RunAndReturn(run func(queueModel ports.QueueModel) (ports.QueueItem, error)) *MockTransformer_Transform_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueExecutor creates a new instance of MockQueueExecutor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueExecutor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueExecutor {
	mock := &MockQueueExecutor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueExecutor is an autogenerated mock type for the QueueExecutor type
type MockQueueExecutor struct {
	mock.Mock
}

type MockQueueExecutor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueExecutor) EXPECT() *MockQueueExecutor_Expecter {
	return &MockQueueExecutor_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockQueueExecutor
func (_mock *MockQueueExecutor) Run(terminatedChan <-chan bool, stoppedChan chan<- bool) error {
	ret := _mock.Called(terminatedChan, stoppedChan)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(<-chan bool, chan<- bool) error); ok {
		r0 = returnFunc(terminatedChan, stoppedChan)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueExecutor_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockQueueExecutor_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - terminatedChan <-chan bool
//   - stoppedChan chan<- bool
func (_e *MockQueueExecutor_Expecter) Run(terminatedChan any, stoppedChan any) *MockQueueExecutor_Run_Call {
	return &MockQueueExecutor_Run_Call{Call: _e.mock.On("Run", terminatedChan, stoppedChan)}
}

func (_c *MockQueueExecutor_Run_Call) Run(run func(terminatedChan <-chan bool, stoppedChan chan<- bool)) *MockQueueExecutor_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 <-chan bool
		if args[0] != nil {
			arg0 = args[0].(<-chan bool)
		}
		var arg1 chan<- bool
		if args[1] != nil {
			arg1 = args[1].(chan<- bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueExecutor_Run_Call) Return(err error) *MockQueueExecutor_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueExecutor_Run_Call) RunAndReturn(run func(terminatedChan <-chan bool, stoppedChan chan<- bool) error) *MockQueueExecutor_Run_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueRepository creates a new instance of MockQueueRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueRepository {
	mock := &MockQueueRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueRepository is an autogenerated mock type for the QueueRepository type
type MockQueueRepository struct {
	mock.Mock
}

type MockQueueRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueRepository) EXPECT() *MockQueueRepository_Expecter {
	return &MockQueueRepository_Expecter{mock: &_m.Mock}
}

// BulkUpdateStatus provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) BulkUpdateStatus(ctx context.Context, updates []ports.QueueItemStatusUpdate) error {
	ret := _mock.Called(ctx, updates)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ports.QueueItemStatusUpdate) error); ok {
		r0 = returnFunc(ctx, updates)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueRepository_BulkUpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdateStatus'
type MockQueueRepository_BulkUpdateStatus_Call struct {
	*mock.Call
}

// BulkUpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - updates []ports.QueueItemStatusUpdate
func (_e *MockQueueRepository_Expecter) BulkUpdateStatus(ctx any, updates any) *MockQueueRepository_BulkUpdateStatus_Call {
	return &MockQueueRepository_BulkUpdateStatus_Call{Call: _e.mock.On("BulkUpdateStatus", ctx, updates)}
}

func (_c *MockQueueRepository_BulkUpdateStatus_Call) Run(run func(ctx context.Context, updates []ports.QueueItemStatusUpdate)) *MockQueueRepository_BulkUpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ports.QueueItemStatusUpdate
		if args[1] != nil {
			arg1 = args[1].([]ports.QueueItemStatusUpdate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueRepository_BulkUpdateStatus_Call) Return(err error) *MockQueueRepository_BulkUpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueRepository_BulkUpdateStatus_Call) RunAndReturn(run func(ctx context.Context, updates []ports.QueueItemStatusUpdate) error) *MockQueueRepository_BulkUpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ClaimReadyItems provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) ClaimReadyItems(ctx context.Context, tag string, at time.Time, limit int) ([]ports.QueueModel, error) {
	ret := _mock.Called(ctx, tag, at, limit)

	if len(ret) == 0 {
		panic("no return value specified for ClaimReadyItems")
	}

	var r0 []ports.QueueModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) ([]ports.QueueModel, error)); ok {
		return returnFunc(ctx, tag, at, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) []ports.QueueModel); ok {
		r0 = returnFunc(ctx, tag, at, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, int) error); ok {
		r1 = returnFunc(ctx, tag, at, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_ClaimReadyItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClaimReadyItems'
type MockQueueRepository_ClaimReadyItems_Call struct {
	*mock.Call
}

// ClaimReadyItems is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - at time.Time
//   - limit int
func (_e *MockQueueRepository_Expecter) ClaimReadyItems(ctx any, tag any, at any, limit any) *MockQueueRepository_ClaimReadyItems_Call {
	return &MockQueueRepository_ClaimReadyItems_Call{Call: _e.mock.On("ClaimReadyItems", ctx, tag, at, limit)}
}

func (_c *MockQueueRepository_ClaimReadyItems_Call) Run(run func(ctx context.Context, tag string, at time.Time, limit int)) *MockQueueRepository_ClaimReadyItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueRepository_ClaimReadyItems_Call) Return(queueModels []ports.QueueModel, err error) *MockQueueRepository_ClaimReadyItems_Call {
	_c.Call.Return(queueModels, err)
	return _c
}

func (_c *MockQueueRepository_ClaimReadyItems_Call) RunAndReturn(run func(ctx context.Context, tag string, at time.Time, limit int) ([]ports.QueueModel, error)) *MockQueueRepository_ClaimReadyItems_Call {
	_c.Call.Return(run)
	return _c
}

// CountByStatuses provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) CountByStatuses(ctx context.Context, tag string, statuses []ports.QueueItemStatus) (int64, error) {
	ret := _mock.Called(ctx, tag, statuses)

	if len(ret) == 0 {
		panic("no return value specified for CountByStatuses")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ports.QueueItemStatus) (int64, error)); ok {
		return returnFunc(ctx, tag, statuses)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []ports.QueueItemStatus) int64); ok {
		r0 = returnFunc(ctx, tag, statuses)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []ports.QueueItemStatus) error); ok {
		r1 = returnFunc(ctx, tag, statuses)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_CountByStatuses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountByStatuses'
type MockQueueRepository_CountByStatuses_Call struct {
	*mock.Call
}

// CountByStatuses is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - statuses []ports.QueueItemStatus
func (_e *MockQueueRepository_Expecter) CountByStatuses(ctx any, tag any, statuses any) *MockQueueRepository_CountByStatuses_Call {
	return &MockQueueRepository_CountByStatuses_Call{Call: _e.mock.On("CountByStatuses", ctx, tag, statuses)}
}

func (_c *MockQueueRepository_CountByStatuses_Call) Run(run func(ctx context.Context, tag string, statuses []ports.QueueItemStatus)) *MockQueueRepository_CountByStatuses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].([]ports.QueueItemStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueRepository_CountByStatuses_Call) Return(n int64, err error) *MockQueueRepository_CountByStatuses_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQueueRepository_CountByStatuses_Call) RunAndReturn(run func(ctx context.Context, tag string, statuses []ports.QueueItemStatus) (int64, error)) *MockQueueRepository_CountByStatuses_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) FindByID(ctx context.Context, id bson.ObjectID) (ports.QueueModel, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 ports.QueueModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (ports.QueueModel, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) ports.QueueModel); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(ports.QueueModel)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type MockQueueRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockQueueRepository_Expecter) FindByID(ctx any, id any) *MockQueueRepository_FindByID_Call {
	return &MockQueueRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *MockQueueRepository_FindByID_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockQueueRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueRepository_FindByID_Call) Return(queueModel ports.QueueModel, err error) *MockQueueRepository_FindByID_Call {
	_c.Call.Return(queueModel, err)
	return _c
}

func (_c *MockQueueRepository_FindByID_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID) (ports.QueueModel, error)) *MockQueueRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStatusAndAction provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) FindByStatusAndAction(ctx context.Context, tag string, status ports.QueueItemStatus, action ports.ActionType) ([]ports.QueueModel, error) {
	ret := _mock.Called(ctx, tag, status, action)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatusAndAction")
	}

	var r0 []ports.QueueModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ports.QueueItemStatus, ports.ActionType) ([]ports.QueueModel, error)); ok {
		return returnFunc(ctx, tag, status, action)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ports.QueueItemStatus, ports.ActionType) []ports.QueueModel); ok {
		r0 = returnFunc(ctx, tag, status, action)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ports.QueueItemStatus, ports.ActionType) error); ok {
		r1 = returnFunc(ctx, tag, status, action)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_FindByStatusAndAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStatusAndAction'
type MockQueueRepository_FindByStatusAndAction_Call struct {
	*mock.Call
}

// FindByStatusAndAction is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - status ports.QueueItemStatus
//   - action ports.ActionType
func (_e *MockQueueRepository_Expecter) FindByStatusAndAction(ctx any, tag any, status any, action any) *MockQueueRepository_FindByStatusAndAction_Call {
	return &MockQueueRepository_FindByStatusAndAction_Call{Call: _e.mock.On("FindByStatusAndAction", ctx, tag, status, action)}
}

func (_c *MockQueueRepository_FindByStatusAndAction_Call) Run(run func(ctx context.Context, tag string, status ports.QueueItemStatus, action ports.ActionType)) *MockQueueRepository_FindByStatusAndAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItemStatus)
		}
		var arg3 ports.ActionType
		if args[3] != nil {
			arg3 = args[3].(ports.ActionType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueRepository_FindByStatusAndAction_Call) Return(queueModels []ports.QueueModel, err error) *MockQueueRepository_FindByStatusAndAction_Call {
	_c.Call.Return(queueModels, err)
	return _c
}

func (_c *MockQueueRepository_FindByStatusAndAction_Call) RunAndReturn(run func(ctx context.Context, tag string, status ports.QueueItemStatus, action ports.ActionType) ([]ports.QueueModel, error)) *MockQueueRepository_FindByStatusAndAction_Call {
	_c.Call.Return(run)
	return _c
}

// FindByStatusAndActions provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) FindByStatusAndActions(ctx context.Context, tag string, status ports.QueueItemStatus, actions []ports.ActionType) ([]ports.QueueModel, error) {
	ret := _mock.Called(ctx, tag, status, actions)

	if len(ret) == 0 {
		panic("no return value specified for FindByStatusAndActions")
	}

	var r0 []ports.QueueModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ports.QueueItemStatus, []ports.ActionType) ([]ports.QueueModel, error)); ok {
		return returnFunc(ctx, tag, status, actions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ports.QueueItemStatus, []ports.ActionType) []ports.QueueModel); ok {
		r0 = returnFunc(ctx, tag, status, actions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ports.QueueItemStatus, []ports.ActionType) error); ok {
		r1 = returnFunc(ctx, tag, status, actions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_FindByStatusAndActions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByStatusAndActions'
type MockQueueRepository_FindByStatusAndActions_Call struct {
	*mock.Call
}

// FindByStatusAndActions is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - status ports.QueueItemStatus
//   - actions []ports.ActionType
func (_e *MockQueueRepository_Expecter) FindByStatusAndActions(ctx any, tag any, status any, actions any) *MockQueueRepository_FindByStatusAndActions_Call {
	return &MockQueueRepository_FindByStatusAndActions_Call{Call: _e.mock.On("FindByStatusAndActions", ctx, tag, status, actions)}
}

func (_c *MockQueueRepository_FindByStatusAndActions_Call) Run(run func(ctx context.Context, tag string, status ports.QueueItemStatus, actions []ports.ActionType)) *MockQueueRepository_FindByStatusAndActions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItemStatus)
		}
		var arg3 []ports.ActionType
		if args[3] != nil {
			arg3 = args[3].([]ports.ActionType)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueRepository_FindByStatusAndActions_Call) Return(queueModels []ports.QueueModel, err error) *MockQueueRepository_FindByStatusAndActions_Call {
	_c.Call.Return(queueModels, err)
	return _c
}

func (_c *MockQueueRepository_FindByStatusAndActions_Call) RunAndReturn(run func(ctx context.Context, tag string, status ports.QueueItemStatus, actions []ports.ActionType) ([]ports.QueueModel, error)) *MockQueueRepository_FindByStatusAndActions_Call {
	_c.Call.Return(run)
	return _c
}

// FindReadyItems provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) FindReadyItems(ctx context.Context, tag string, at time.Time, limit int) ([]ports.QueueModel, error) {
	ret := _mock.Called(ctx, tag, at, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindReadyItems")
	}

	var r0 []ports.QueueModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) ([]ports.QueueModel, error)); ok {
		return returnFunc(ctx, tag, at, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Time, int) []ports.QueueModel); ok {
		r0 = returnFunc(ctx, tag, at, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Time, int) error); ok {
		r1 = returnFunc(ctx, tag, at, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_FindReadyItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindReadyItems'
type MockQueueRepository_FindReadyItems_Call struct {
	*mock.Call
}

// FindReadyItems is a helper method to define mock.On call
//   - ctx context.Context
//   - tag string
//   - at time.Time
//   - limit int
func (_e *MockQueueRepository_Expecter) FindReadyItems(ctx any, tag any, at any, limit any) *MockQueueRepository_FindReadyItems_Call {
	return &MockQueueRepository_FindReadyItems_Call{Call: _e.mock.On("FindReadyItems", ctx, tag, at, limit)}
}

func (_c *MockQueueRepository_FindReadyItems_Call) Run(run func(ctx context.Context, tag string, at time.Time, limit int)) *MockQueueRepository_FindReadyItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueRepository_FindReadyItems_Call) Return(queueModels []ports.QueueModel, err error) *MockQueueRepository_FindReadyItems_Call {
	_c.Call.Return(queueModels, err)
	return _c
}

func (_c *MockQueueRepository_FindReadyItems_Call) RunAndReturn(run func(ctx context.Context, tag string, at time.Time, limit int) ([]ports.QueueModel, error)) *MockQueueRepository_FindReadyItems_Call {
	_c.Call.Return(run)
	return _c
}

// InsertItem provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) InsertItem(ctx context.Context, item ports.QueueModel) (bson.ObjectID, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for InsertItem")
	}

	var r0 bson.ObjectID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.QueueModel) (bson.ObjectID, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.QueueModel) bson.ObjectID); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.ObjectID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.QueueModel) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_InsertItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertItem'
type MockQueueRepository_InsertItem_Call struct {
	*mock.Call
}

// InsertItem is a helper method to define mock.On call
//   - ctx context.Context
//   - item ports.QueueModel
func (_e *MockQueueRepository_Expecter) InsertItem(ctx any, item any) *MockQueueRepository_InsertItem_Call {
	return &MockQueueRepository_InsertItem_Call{Call: _e.mock.On("InsertItem", ctx, item)}
}

func (_c *MockQueueRepository_InsertItem_Call) Run(run func(ctx context.Context, item ports.QueueModel)) *MockQueueRepository_InsertItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.QueueModel
		if args[1] != nil {
			arg1 = args[1].(ports.QueueModel)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueRepository_InsertItem_Call) Return(objectID bson.ObjectID, err error) *MockQueueRepository_InsertItem_Call {
	_c.Call.Return(objectID, err)
	return _c
}

func (_c *MockQueueRepository_InsertItem_Call) RunAndReturn(run func(ctx context.Context, item ports.QueueModel) (bson.ObjectID, error)) *MockQueueRepository_InsertItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) ListItems(ctx context.Context, filter ports.ListQueueItemsFilter) ([]ports.QueueModel, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []ports.QueueModel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ListQueueItemsFilter) ([]ports.QueueModel, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ListQueueItemsFilter) []ports.QueueModel); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueModel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.ListQueueItemsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueRepository_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type MockQueueRepository_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ports.ListQueueItemsFilter
func (_e *MockQueueRepository_Expecter) ListItems(ctx any, filter any) *MockQueueRepository_ListItems_Call {
	return &MockQueueRepository_ListItems_Call{Call: _e.mock.On("ListItems", ctx, filter)}
}

func (_c *MockQueueRepository_ListItems_Call) Run(run func(ctx context.Context, filter ports.ListQueueItemsFilter)) *MockQueueRepository_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.ListQueueItemsFilter
		if args[1] != nil {
			arg1 = args[1].(ports.ListQueueItemsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueRepository_ListItems_Call) Return(queueModels []ports.QueueModel, err error) *MockQueueRepository_ListItems_Call {
	_c.Call.Return(queueModels, err)
	return _c
}

func (_c *MockQueueRepository_ListItems_Call) RunAndReturn(run func(ctx context.Context, filter ports.ListQueueItemsFilter) ([]ports.QueueModel, error)) *MockQueueRepository_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// RescheduleItem provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) RescheduleItem(ctx context.Context, id bson.ObjectID, scheduledAt time.Time, message string) error {
	ret := _mock.Called(ctx, id, scheduledAt, message)

	if len(ret) == 0 {
		panic("no return value specified for RescheduleItem")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID, time.Time, string) error); ok {
		r0 = returnFunc(ctx, id, scheduledAt, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueRepository_RescheduleItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RescheduleItem'
type MockQueueRepository_RescheduleItem_Call struct {
	*mock.Call
}

// RescheduleItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
//   - scheduledAt time.Time
//   - message string
func (_e *MockQueueRepository_Expecter) RescheduleItem(ctx any, id any, scheduledAt any, message any) *MockQueueRepository_RescheduleItem_Call {
	return &MockQueueRepository_RescheduleItem_Call{Call: _e.mock.On("RescheduleItem", ctx, id, scheduledAt, message)}
}

func (_c *MockQueueRepository_RescheduleItem_Call) Run(run func(ctx context.Context, id bson.ObjectID, scheduledAt time.Time, message string)) *MockQueueRepository_RescheduleItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueRepository_RescheduleItem_Call) Return(err error) *MockQueueRepository_RescheduleItem_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueRepository_RescheduleItem_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID, scheduledAt time.Time, message string) error) *MockQueueRepository_RescheduleItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateData provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) UpdateData(ctx context.Context, id bson.ObjectID, data any) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for UpdateData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID, any) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueRepository_UpdateData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateData'
type MockQueueRepository_UpdateData_Call struct {
	*mock.Call
}

// UpdateData is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
//   - data any
func (_e *MockQueueRepository_Expecter) UpdateData(ctx any, id any, data any) *MockQueueRepository_UpdateData_Call {
	return &MockQueueRepository_UpdateData_Call{Call: _e.mock.On("UpdateData", ctx, id, data)}
}

func (_c *MockQueueRepository_UpdateData_Call) Run(run func(ctx context.Context, id bson.ObjectID, data any)) *MockQueueRepository_UpdateData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueRepository_UpdateData_Call) Return(err error) *MockQueueRepository_UpdateData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueRepository_UpdateData_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID, data any) error) *MockQueueRepository_UpdateData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateManyStatus provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) UpdateManyStatus(ctx context.Context, ids []bson.ObjectID, status ports.QueueItemStatus, message string) error {
	ret := _mock.Called(ctx, ids, status, message)

	if len(ret) == 0 {
		panic("no return value specified for UpdateManyStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []bson.ObjectID, ports.QueueItemStatus, string) error); ok {
		r0 = returnFunc(ctx, ids, status, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueRepository_UpdateManyStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateManyStatus'
type MockQueueRepository_UpdateManyStatus_Call struct {
	*mock.Call
}

// UpdateManyStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []bson.ObjectID
//   - status ports.QueueItemStatus
//   - message string
func (_e *MockQueueRepository_Expecter) UpdateManyStatus(ctx any, ids any, status any, message any) *MockQueueRepository_UpdateManyStatus_Call {
	return &MockQueueRepository_UpdateManyStatus_Call{Call: _e.mock.On("UpdateManyStatus", ctx, ids, status, message)}
}

func (_c *MockQueueRepository_UpdateManyStatus_Call) Run(run func(ctx context.Context, ids []bson.ObjectID, status ports.QueueItemStatus, message string)) *MockQueueRepository_UpdateManyStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].([]bson.ObjectID)
		}
		var arg2 ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItemStatus)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueRepository_UpdateManyStatus_Call) Return(err error) *MockQueueRepository_UpdateManyStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueRepository_UpdateManyStatus_Call) RunAndReturn(run func(ctx context.Context, ids []bson.ObjectID, status ports.QueueItemStatus, message string) error) *MockQueueRepository_UpdateManyStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function for the type MockQueueRepository
func (_mock *MockQueueRepository) UpdateStatus(ctx context.Context, id bson.ObjectID, status ports.QueueItemStatus, message string) error {
	ret := _mock.Called(ctx, id, status, message)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID, ports.QueueItemStatus, string) error); ok {
		r0 = returnFunc(ctx, id, status, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueRepository_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type MockQueueRepository_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
//   - status ports.QueueItemStatus
//   - message string
func (_e *MockQueueRepository_Expecter) UpdateStatus(ctx any, id any, status any, message any) *MockQueueRepository_UpdateStatus_Call {
	return &MockQueueRepository_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, id, status, message)}
}

func (_c *MockQueueRepository_UpdateStatus_Call) Run(run func(ctx context.Context, id bson.ObjectID, status ports.QueueItemStatus, message string)) *MockQueueRepository_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		var arg2 ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItemStatus)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockQueueRepository_UpdateStatus_Call) Return(err error) *MockQueueRepository_UpdateStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueRepository_UpdateStatus_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID, status ports.QueueItemStatus, message string) error) *MockQueueRepository_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueueService creates a new instance of MockQueueService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueueService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueueService {
	mock := &MockQueueService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueueService is an autogenerated mock type for the QueueService type
type MockQueueService struct {
	mock.Mock
}

type MockQueueService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueueService) EXPECT() *MockQueueService_Expecter {
	return &MockQueueService_Expecter{mock: &_m.Mock}
}

// BulkCancel provides a mock function for the type MockQueueService
func (_mock *MockQueueService) BulkCancel(ctx context.Context, ids []bson.ObjectID, reason ...string) error {
	var tmpRet mock.Arguments
	if len(reason) > 0 {
		tmpRet = _mock.Called(ctx, ids, reason)
	} else {
		tmpRet = _mock.Called(ctx, ids)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BulkCancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []bson.ObjectID, ...string) error); ok {
		r0 = returnFunc(ctx, ids, reason...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueService_BulkCancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkCancel'
type MockQueueService_BulkCancel_Call struct {
	*mock.Call
}

// BulkCancel is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []bson.ObjectID
//   - reason ...string
func (_e *MockQueueService_Expecter) BulkCancel(ctx any, ids any, reason ...any) *MockQueueService_BulkCancel_Call {
	return &MockQueueService_BulkCancel_Call{Call: _e.mock.On("BulkCancel",
		append([]any{ctx, ids}, reason...)...)}
}

func (_c *MockQueueService_BulkCancel_Call) Run(run func(ctx context.Context, ids []bson.ObjectID, reason ...string)) *MockQueueService_BulkCancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].([]bson.ObjectID)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueueService_BulkCancel_Call) Return(err error) *MockQueueService_BulkCancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueService_BulkCancel_Call) RunAndReturn(run func(ctx context.Context, ids []bson.ObjectID, reason ...string) error) *MockQueueService_BulkCancel_Call {
	_c.Call.Return(run)
	return _c
}

// Cancel provides a mock function for the type MockQueueService
func (_mock *MockQueueService) Cancel(ctx context.Context, id bson.ObjectID, reason ...string) error {
	var tmpRet mock.Arguments
	if len(reason) > 0 {
		tmpRet = _mock.Called(ctx, id, reason)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID, ...string) error); ok {
		r0 = returnFunc(ctx, id, reason...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueService_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockQueueService_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
//   - reason ...string
func (_e *MockQueueService_Expecter) Cancel(ctx any, id any, reason ...any) *MockQueueService_Cancel_Call {
	return &MockQueueService_Cancel_Call{Call: _e.mock.On("Cancel",
		append([]any{ctx, id}, reason...)...)}
}

func (_c *MockQueueService_Cancel_Call) Run(run func(ctx context.Context, id bson.ObjectID, reason ...string)) *MockQueueService_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		var arg2 []string
		var variadicArgs []string
		if len(args) > 2 {
			variadicArgs = args[2].([]string)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueueService_Cancel_Call) Return(err error) *MockQueueService_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueService_Cancel_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID, reason ...string) error) *MockQueueService_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Dequeue provides a mock function for the type MockQueueService
func (_mock *MockQueueService) Dequeue(ctx context.Context, fn func(ports.QueueItem) error, options ...ports.DequeueOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, fn, options)
	} else {
		tmpRet = _mock.Called(ctx, fn)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Dequeue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ports.QueueItem) error, ...ports.DequeueOption) error); ok {
		r0 = returnFunc(ctx, fn, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueService_Dequeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dequeue'
type MockQueueService_Dequeue_Call struct {
	*mock.Call
}

// Dequeue is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ports.QueueItem) error
//   - options ...ports.DequeueOption
func (_e *MockQueueService_Expecter) Dequeue(ctx any, fn any, options ...any) *MockQueueService_Dequeue_Call {
	return &MockQueueService_Dequeue_Call{Call: _e.mock.On("Dequeue",
		append([]any{ctx, fn}, options...)...)}
}

func (_c *MockQueueService_Dequeue_Call) Run(run func(ctx context.Context, fn func(ports.QueueItem) error, options ...ports.DequeueOption)) *MockQueueService_Dequeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ports.QueueItem) error
		if args[1] != nil {
			arg1 = args[1].(func(ports.QueueItem) error)
		}
		var arg2 []ports.DequeueOption
		var variadicArgs []ports.DequeueOption
		if len(args) > 2 {
			variadicArgs = args[2].([]ports.DequeueOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueueService_Dequeue_Call) Return(err error) *MockQueueService_Dequeue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueService_Dequeue_Call) RunAndReturn(run func(ctx context.Context, fn func(ports.QueueItem) error, options ...ports.DequeueOption) error) *MockQueueService_Dequeue_Call {
	_c.Call.Return(run)
	return _c
}

// DequeueWithManualAck provides a mock function for the type MockQueueService
func (_mock *MockQueueService) DequeueWithManualAck(ctx context.Context, item func(ports.QueueItem) (ports.QueueItemStatus, error), options ...ports.DequeueOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(ctx, item, options)
	} else {
		tmpRet = _mock.Called(ctx, item)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DequeueWithManualAck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ports.QueueItem) (ports.QueueItemStatus, error), ...ports.DequeueOption) error); ok {
		r0 = returnFunc(ctx, item, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueService_DequeueWithManualAck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DequeueWithManualAck'
type MockQueueService_DequeueWithManualAck_Call struct {
	*mock.Call
}

// DequeueWithManualAck is a helper method to define mock.On call
//   - ctx context.Context
//   - item func(ports.QueueItem) (ports.QueueItemStatus, error)
//   - options ...ports.DequeueOption
func (_e *MockQueueService_Expecter) DequeueWithManualAck(ctx any, item any, options ...any) *MockQueueService_DequeueWithManualAck_Call {
	return &MockQueueService_DequeueWithManualAck_Call{Call: _e.mock.On("DequeueWithManualAck",
		append([]any{ctx, item}, options...)...)}
}

func (_c *MockQueueService_DequeueWithManualAck_Call) Run(run func(ctx context.Context, item func(ports.QueueItem) (ports.QueueItemStatus, error), options ...ports.DequeueOption)) *MockQueueService_DequeueWithManualAck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ports.QueueItem) (ports.QueueItemStatus, error)
		if args[1] != nil {
			arg1 = args[1].(func(ports.QueueItem) (ports.QueueItemStatus, error))
		}
		var arg2 []ports.DequeueOption
		var variadicArgs []ports.DequeueOption
		if len(args) > 2 {
			variadicArgs = args[2].([]ports.DequeueOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueueService_DequeueWithManualAck_Call) Return(err error) *MockQueueService_DequeueWithManualAck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueService_DequeueWithManualAck_Call) RunAndReturn(run func(ctx context.Context, item func(ports.QueueItem) (ports.QueueItemStatus, error), options ...ports.DequeueOption) error) *MockQueueService_DequeueWithManualAck_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type MockQueueService
func (_mock *MockQueueService) Enqueue(ctx context.Context, item ports.QueueItem) (bson.ObjectID, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 bson.ObjectID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.QueueItem) (bson.ObjectID, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.QueueItem) bson.ObjectID); ok {
		r0 = returnFunc(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(bson.ObjectID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.QueueItem) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueService_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueueService_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - item ports.QueueItem
func (_e *MockQueueService_Expecter) Enqueue(ctx any, item any) *MockQueueService_Enqueue_Call {
	return &MockQueueService_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, item)}
}

func (_c *MockQueueService_Enqueue_Call) Run(run func(ctx context.Context, item ports.QueueItem)) *MockQueueService_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.QueueItem
		if args[1] != nil {
			arg1 = args[1].(ports.QueueItem)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueService_Enqueue_Call) Return(objectID bson.ObjectID, err error) *MockQueueService_Enqueue_Call {
	_c.Call.Return(objectID, err)
	return _c
}

func (_c *MockQueueService_Enqueue_Call) RunAndReturn(run func(ctx context.Context, item ports.QueueItem) (bson.ObjectID, error)) *MockQueueService_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Filter provides a mock function for the type MockQueueService
func (_mock *MockQueueService) Filter(ctx context.Context, action ports.ActionType, status ports.QueueItemStatus) ([]ports.QueueItem, error) {
	ret := _mock.Called(ctx, action, status)

	if len(ret) == 0 {
		panic("no return value specified for Filter")
	}

	var r0 []ports.QueueItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ActionType, ports.QueueItemStatus) ([]ports.QueueItem, error)); ok {
		return returnFunc(ctx, action, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ActionType, ports.QueueItemStatus) []ports.QueueItem); ok {
		r0 = returnFunc(ctx, action, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.ActionType, ports.QueueItemStatus) error); ok {
		r1 = returnFunc(ctx, action, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueService_Filter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filter'
type MockQueueService_Filter_Call struct {
	*mock.Call
}

// Filter is a helper method to define mock.On call
//   - ctx context.Context
//   - action ports.ActionType
//   - status ports.QueueItemStatus
func (_e *MockQueueService_Expecter) Filter(ctx any, action any, status any) *MockQueueService_Filter_Call {
	return &MockQueueService_Filter_Call{Call: _e.mock.On("Filter", ctx, action, status)}
}

func (_c *MockQueueService_Filter_Call) Run(run func(ctx context.Context, action ports.ActionType, status ports.QueueItemStatus)) *MockQueueService_Filter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.ActionType
		if args[1] != nil {
			arg1 = args[1].(ports.ActionType)
		}
		var arg2 ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItemStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueService_Filter_Call) Return(queueItems []ports.QueueItem, err error) *MockQueueService_Filter_Call {
	_c.Call.Return(queueItems, err)
	return _c
}

func (_c *MockQueueService_Filter_Call) RunAndReturn(run func(ctx context.Context, action ports.ActionType, status ports.QueueItemStatus) ([]ports.QueueItem, error)) *MockQueueService_Filter_Call {
	_c.Call.Return(run)
	return _c
}

// Filters provides a mock function for the type MockQueueService
func (_mock *MockQueueService) Filters(ctx context.Context, actions []ports.ActionType, status ports.QueueItemStatus) ([]ports.QueueItem, error) {
	ret := _mock.Called(ctx, actions, status)

	if len(ret) == 0 {
		panic("no return value specified for Filters")
	}

	var r0 []ports.QueueItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ports.ActionType, ports.QueueItemStatus) ([]ports.QueueItem, error)); ok {
		return returnFunc(ctx, actions, status)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []ports.ActionType, ports.QueueItemStatus) []ports.QueueItem); ok {
		r0 = returnFunc(ctx, actions, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []ports.ActionType, ports.QueueItemStatus) error); ok {
		r1 = returnFunc(ctx, actions, status)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueService_Filters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Filters'
type MockQueueService_Filters_Call struct {
	*mock.Call
}

// Filters is a helper method to define mock.On call
//   - ctx context.Context
//   - actions []ports.ActionType
//   - status ports.QueueItemStatus
func (_e *MockQueueService_Expecter) Filters(ctx any, actions any, status any) *MockQueueService_Filters_Call {
	return &MockQueueService_Filters_Call{Call: _e.mock.On("Filters", ctx, actions, status)}
}

func (_c *MockQueueService_Filters_Call) Run(run func(ctx context.Context, actions []ports.ActionType, status ports.QueueItemStatus)) *MockQueueService_Filters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []ports.ActionType
		if args[1] != nil {
			arg1 = args[1].([]ports.ActionType)
		}
		var arg2 ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItemStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueService_Filters_Call) Return(queueItems []ports.QueueItem, err error) *MockQueueService_Filters_Call {
	_c.Call.Return(queueItems, err)
	return _c
}

func (_c *MockQueueService_Filters_Call) RunAndReturn(run func(ctx context.Context, actions []ports.ActionType, status ports.QueueItemStatus) ([]ports.QueueItem, error)) *MockQueueService_Filters_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type MockQueueService
func (_mock *MockQueueService) GetItem(ctx context.Context, id bson.ObjectID) (ports.QueueItem, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 ports.QueueItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (ports.QueueItem, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) ports.QueueItem); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.QueueItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueService_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type MockQueueService_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockQueueService_Expecter) GetItem(ctx any, id any) *MockQueueService_GetItem_Call {
	return &MockQueueService_GetItem_Call{Call: _e.mock.On("GetItem", ctx, id)}
}

func (_c *MockQueueService_GetItem_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockQueueService_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueService_GetItem_Call) Return(queueItem ports.QueueItem, err error) *MockQueueService_GetItem_Call {
	_c.Call.Return(queueItem, err)
	return _c
}

func (_c *MockQueueService_GetItem_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID) (ports.QueueItem, error)) *MockQueueService_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueueData provides a mock function for the type MockQueueService
func (_mock *MockQueueService) GetQueueData(ctx context.Context, id bson.ObjectID) (ports.QueueItem, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetQueueData")
	}

	var r0 ports.QueueItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (ports.QueueItem, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) ports.QueueItem); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.QueueItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueService_GetQueueData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueData'
type MockQueueService_GetQueueData_Call struct {
	*mock.Call
}

// GetQueueData is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockQueueService_Expecter) GetQueueData(ctx any, id any) *MockQueueService_GetQueueData_Call {
	return &MockQueueService_GetQueueData_Call{Call: _e.mock.On("GetQueueData", ctx, id)}
}

func (_c *MockQueueService_GetQueueData_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockQueueService_GetQueueData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueService_GetQueueData_Call) Return(queueItem ports.QueueItem, err error) *MockQueueService_GetQueueData_Call {
	_c.Call.Return(queueItem, err)
	return _c
}

func (_c *MockQueueService_GetQueueData_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID) (ports.QueueItem, error)) *MockQueueService_GetQueueData_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockQueueService
func (_mock *MockQueueService) GetStatus(ctx context.Context, id bson.ObjectID) (ports.QueueItemStatus, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 ports.QueueItemStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (ports.QueueItemStatus, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) ports.QueueItemStatus); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(ports.QueueItemStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueService_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockQueueService_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockQueueService_Expecter) GetStatus(ctx any, id any) *MockQueueService_GetStatus_Call {
	return &MockQueueService_GetStatus_Call{Call: _e.mock.On("GetStatus", ctx, id)}
}

func (_c *MockQueueService_GetStatus_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockQueueService_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueService_GetStatus_Call) Return(queueItemStatus ports.QueueItemStatus, err error) *MockQueueService_GetStatus_Call {
	_c.Call.Return(queueItemStatus, err)
	return _c
}

func (_c *MockQueueService_GetStatus_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID) (ports.QueueItemStatus, error)) *MockQueueService_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusWithMessage provides a mock function for the type MockQueueService
func (_mock *MockQueueService) GetStatusWithMessage(ctx context.Context, id bson.ObjectID) (ports.QueueItemStatus, string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusWithMessage")
	}

	var r0 ports.QueueItemStatus
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) (ports.QueueItemStatus, string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID) ports.QueueItemStatus); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(ports.QueueItemStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bson.ObjectID) string); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, bson.ObjectID) error); ok {
		r2 = returnFunc(ctx, id)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockQueueService_GetStatusWithMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusWithMessage'
type MockQueueService_GetStatusWithMessage_Call struct {
	*mock.Call
}

// GetStatusWithMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
func (_e *MockQueueService_Expecter) GetStatusWithMessage(ctx any, id any) *MockQueueService_GetStatusWithMessage_Call {
	return &MockQueueService_GetStatusWithMessage_Call{Call: _e.mock.On("GetStatusWithMessage", ctx, id)}
}

func (_c *MockQueueService_GetStatusWithMessage_Call) Run(run func(ctx context.Context, id bson.ObjectID)) *MockQueueService_GetStatusWithMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueService_GetStatusWithMessage_Call) Return(queueItemStatus ports.QueueItemStatus, s string, err error) *MockQueueService_GetStatusWithMessage_Call {
	_c.Call.Return(queueItemStatus, s, err)
	return _c
}

func (_c *MockQueueService_GetStatusWithMessage_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID) (ports.QueueItemStatus, string, error)) *MockQueueService_GetStatusWithMessage_Call {
	_c.Call.Return(run)
	return _c
}

// GetTag provides a mock function for the type MockQueueService
func (_mock *MockQueueService) GetTag() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTag")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockQueueService_GetTag_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTag'
type MockQueueService_GetTag_Call struct {
	*mock.Call
}

// GetTag is a helper method to define mock.On call
func (_e *MockQueueService_Expecter) GetTag() *MockQueueService_GetTag_Call {
	return &MockQueueService_GetTag_Call{Call: _e.mock.On("GetTag")}
}

func (_c *MockQueueService_GetTag_Call) Run(run func()) *MockQueueService_GetTag_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueueService_GetTag_Call) Return(s string) *MockQueueService_GetTag_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockQueueService_GetTag_Call) RunAndReturn(run func() string) *MockQueueService_GetTag_Call {
	_c.Call.Return(run)
	return _c
}

// IsEmpty provides a mock function for the type MockQueueService
func (_mock *MockQueueService) IsEmpty(ctx context.Context) bool {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsEmpty")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockQueueService_IsEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEmpty'
type MockQueueService_IsEmpty_Call struct {
	*mock.Call
}

// IsEmpty is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueueService_Expecter) IsEmpty(ctx any) *MockQueueService_IsEmpty_Call {
	return &MockQueueService_IsEmpty_Call{Call: _e.mock.On("IsEmpty", ctx)}
}

func (_c *MockQueueService_IsEmpty_Call) Run(run func(ctx context.Context)) *MockQueueService_IsEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueueService_IsEmpty_Call) Return(b bool) *MockQueueService_IsEmpty_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockQueueService_IsEmpty_Call) RunAndReturn(run func(ctx context.Context) bool) *MockQueueService_IsEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// ListItems provides a mock function for the type MockQueueService
func (_mock *MockQueueService) ListItems(ctx context.Context, filter ports.ListQueueItemsFilter) ([]ports.QueueItem, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListItems")
	}

	var r0 []ports.QueueItem
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ListQueueItemsFilter) ([]ports.QueueItem, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ports.ListQueueItemsFilter) []ports.QueueItem); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ports.QueueItem)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ports.ListQueueItemsFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueueService_ListItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListItems'
type MockQueueService_ListItems_Call struct {
	*mock.Call
}

// ListItems is a helper method to define mock.On call
//   - ctx context.Context
//   - filter ports.ListQueueItemsFilter
func (_e *MockQueueService_Expecter) ListItems(ctx any, filter any) *MockQueueService_ListItems_Call {
	return &MockQueueService_ListItems_Call{Call: _e.mock.On("ListItems", ctx, filter)}
}

func (_c *MockQueueService_ListItems_Call) Run(run func(ctx context.Context, filter ports.ListQueueItemsFilter)) *MockQueueService_ListItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ports.ListQueueItemsFilter
		if args[1] != nil {
			arg1 = args[1].(ports.ListQueueItemsFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueueService_ListItems_Call) Return(queueItems []ports.QueueItem, err error) *MockQueueService_ListItems_Call {
	_c.Call.Return(queueItems, err)
	return _c
}

func (_c *MockQueueService_ListItems_Call) RunAndReturn(run func(ctx context.Context, filter ports.ListQueueItemsFilter) ([]ports.QueueItem, error)) *MockQueueService_ListItems_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQueueItemData provides a mock function for the type MockQueueService
func (_mock *MockQueueService) UpdateQueueItemData(ctx context.Context, id bson.ObjectID, item ports.QueueItem) error {
	ret := _mock.Called(ctx, id, item)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQueueItemData")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID, ports.QueueItem) error); ok {
		r0 = returnFunc(ctx, id, item)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueService_UpdateQueueItemData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQueueItemData'
type MockQueueService_UpdateQueueItemData_Call struct {
	*mock.Call
}

// UpdateQueueItemData is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
//   - item ports.QueueItem
func (_e *MockQueueService_Expecter) UpdateQueueItemData(ctx any, id any, item any) *MockQueueService_UpdateQueueItemData_Call {
	return &MockQueueService_UpdateQueueItemData_Call{Call: _e.mock.On("UpdateQueueItemData", ctx, id, item)}
}

func (_c *MockQueueService_UpdateQueueItemData_Call) Run(run func(ctx context.Context, id bson.ObjectID, item ports.QueueItem)) *MockQueueService_UpdateQueueItemData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		var arg2 ports.QueueItem
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItem)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueService_UpdateQueueItemData_Call) Return(err error) *MockQueueService_UpdateQueueItemData_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueService_UpdateQueueItemData_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID, item ports.QueueItem) error) *MockQueueService_UpdateQueueItemData_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateQueueItemStatus provides a mock function for the type MockQueueService
func (_mock *MockQueueService) UpdateQueueItemStatus(ctx context.Context, id bson.ObjectID, status ports.QueueItemStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateQueueItemStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bson.ObjectID, ports.QueueItemStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueueService_UpdateQueueItemStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateQueueItemStatus'
type MockQueueService_UpdateQueueItemStatus_Call struct {
	*mock.Call
}

// UpdateQueueItemStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id bson.ObjectID
//   - status ports.QueueItemStatus
func (_e *MockQueueService_Expecter) UpdateQueueItemStatus(ctx any, id any, status any) *MockQueueService_UpdateQueueItemStatus_Call {
	return &MockQueueService_UpdateQueueItemStatus_Call{Call: _e.mock.On("UpdateQueueItemStatus", ctx, id, status)}
}

func (_c *MockQueueService_UpdateQueueItemStatus_Call) Run(run func(ctx context.Context, id bson.ObjectID, status ports.QueueItemStatus)) *MockQueueService_UpdateQueueItemStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bson.ObjectID
		if args[1] != nil {
			arg1 = args[1].(bson.ObjectID)
		}
		var arg2 ports.QueueItemStatus
		if args[2] != nil {
			arg2 = args[2].(ports.QueueItemStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueueService_UpdateQueueItemStatus_Call) Return(err error) *MockQueueService_UpdateQueueItemStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueueService_UpdateQueueItemStatus_Call) RunAndReturn(run func(ctx context.Context, id bson.ObjectID, status ports.QueueItemStatus) error) *MockQueueService_UpdateQueueItemStatus_Call {
	_c.Call.Return(run)
	return _c
}
