package generator

const FieldTemplateCore = `// Field represents a type-safe query field for MongoDB.
type Field[T any] struct {
	key string
}

// NewField creates a new Field with the given bson key.
func NewField[T any](key string) Field[T] {
	return Field[T]{key: key}
}

// Key returns the underlying BSON field name.
func (f Field[T]) Key() string {
	return f.key
}

// Eq matches values that are equal to val ($eq).
func (f Field[T]) Eq(val T) bson.E {
	return bson.E{Key: f.key, Value: val}
}

// Ne matches all values that are not equal to val ($ne).
func (f Field[T]) Ne(val T) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$ne", Value: val} }}
}

// Gt matches values that are greater than val ($gt).
func (f Field[T]) Gt(val T) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$gt", Value: val} }}
}

// Gte matches values that are greater than or equal to val ($gte).
func (f Field[T]) Gte(val T) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$gte", Value: val} }}
}

// Lt matches values that are less than val ($lt).
func (f Field[T]) Lt(val T) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$lt", Value: val} }}
}

// Lte matches values that are less than or equal to val ($lte).
func (f Field[T]) Lte(val T) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$lte", Value: val} }}
}

// In matches any of the values specified in the array ($in).
func (f Field[T]) In(vals ...T) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$in", Value: vals} }}
}

// Nin matches none of the values specified in the array ($nin).
func (f Field[T]) Nin(vals ...T) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$nin", Value: vals} }}
}

// Exists matches documents that have the specified field ($exists).
func (f Field[T]) Exists(exists bool) bson.E {
	return bson.E{Key: f.key, Value: bson.D{ {Key: "$exists", Value: exists} }}
}

// Asc returns a bson.E for ascending index or sort order.
func (f Field[T]) Asc() bson.E {
	return bson.E{Key: f.key, Value: 1}
}

// Desc returns a bson.E for descending index or sort order.
func (f Field[T]) Desc() bson.E {
	return bson.E{Key: f.key, Value: -1}
}

// Unset returns a bson.E for $unset updates.
func (f Field[T]) Unset() bson.E {
	return bson.E{Key: f.key, Value: ""}
}

// Common type aliases for convenience
type StringField = Field[string]
type IntField = Field[int]
type Int64Field = Field[int64]
type BoolField = Field[bool]
type ObjectIDField = Field[bson.ObjectID]
type TimeField = Field[time.Time]
type AnyField = Field[any]
`

const FieldTemplate = `// Code generated by mongo-generator. DO NOT EDIT.

package {{.PackageName}}

import (
	"time"

	"go.mongodb.org/mongo-driver/v2/bson"
)

` + FieldTemplateCore

// ModelTemplate renders a shared-mode model file: Field[T] itself is not
// defined here, it is imported (aliased as .FieldPkg) from the framework's
// mongo package, since Field[T] never varies per project.
const ModelTemplate = `// Code generated by mongo-generator. DO NOT EDIT.

package {{.PackageName}}

import (
{{range .Imports}}	"{{.}}"
{{end}})

{{define "fieldDef"}}
	{{.GoName}} {{if .SubFields}}struct {
		{{.FieldPkg}}Field[{{.GoType}}]
		{{range .SubFields}}{{template "fieldDef" .}}{{end}}
	}{{else}}{{.FieldPkg}}Field[{{.GoType}}]{{end}}
{{end}}

{{define "fieldVal"}}
	{{.GoName}}: {{if .SubFields}}struct {
		{{.FieldPkg}}Field[{{.GoType}}]
		{{range .SubFields}}{{template "fieldDef" .}}{{end}}
	}{
		Field: {{.FieldPkg}}NewField[{{.GoType}}]("{{.BsonKey}}"),
		{{range .SubFields}}{{template "fieldVal" .}}{{end}}
	},{{else}}{{.FieldPkg}}NewField[{{.GoType}}]("{{.BsonKey}}"),{{end}}
{{end}}

var {{.StructName}} = struct {
{{range .Fields}}{{template "fieldDef" .}}
{{end}}}{
{{range .Fields}}{{template "fieldVal" .}}
{{end}}}
{{if .HasAlias}}
var {{.VarName}} = {{.StructName}}
{{end}}
`

const StandaloneModelTemplate = `// Code generated by mongo-generator. DO NOT EDIT.

package {{.PackageName}}

import (
{{range .Imports}}	"{{.}}"
{{end}})

` + FieldTemplateCore + `
{{define "standaloneFieldDef"}}
	{{.GoName}} {{if .SubFields}}struct {
		Field[{{.GoType}}]
		{{range .SubFields}}{{template "standaloneFieldDef" .}}{{end}}
	}{{else}}{{.FieldType}}{{end}}
{{end}}

{{define "standaloneFieldVal"}}
	{{.GoName}}: {{if .SubFields}}struct {
		Field[{{.GoType}}]
		{{range .SubFields}}{{template "standaloneFieldDef" .}}{{end}}
	}{
		Field: Field[{{.GoType}}]{key: "{{.BsonKey}}"},
		{{range .SubFields}}{{template "standaloneFieldVal" .}}{{end}}
	},{{else}}{{.FieldType}}{key: "{{.BsonKey}}"},{{end}}
{{end}}

var {{.StructName}} = struct {
{{range .Fields}}{{template "standaloneFieldDef" .}}
{{end}}}{
{{range .Fields}}{{template "standaloneFieldVal" .}}
{{end}}}
{{if .HasAlias}}
var {{.VarName}} = {{.StructName}}
{{end}}
`
